// Research Methods & Tips Knowledge Base
// Authored best-practice tips, tricks, and advanced methods to raise research
// quality, speed, originality, and significance. First-party expertise —
// evidenceLevel is marked honestly.

export type TipCategory =
  | "planning"
  | "writing"
  | "structure"
  | "statistics"
  | "reproducibility"
  | "literature"
  | "figures"
  | "publishing"
  | "revision"
  | "ethics"
  | "productivity"
  | "originality";

export type EvidenceLevel = "established-practice" | "expert-opinion";

export type ResearchTip = {
  id: string;
  title: string;
  category: TipCategory;
  insight: string;
  why: string;
  how: string;
  evidenceLevel?: EvidenceLevel;
};

export const researchTips: ResearchTip[] = [
  // ── PLANNING
  {
    id: "tip-target-journal-first",
    title: "Target the journal before writing",
    category: "planning",
    insight: "Choose your target journal before drafting, not after rejection.",
    why: "Scope, structure, word limits, and audience differ sharply by journal; writing blind wastes rounds of reformatting.",
    how: "Shortlist 2-3 journals whose scope fits, read recent similar articles, and draft to the strongest candidate's structure and limits.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-checklist-before-draft",
    title: "Use a reporting checklist before the first draft",
    category: "planning",
    insight: "Open the matching EQUATOR checklist before you write, not at submission.",
    why: "Retrofitting a checklist after drafting reveals missing design details that can no longer be recovered.",
    how: "Identify your design, pull the right guideline (CONSORT/STROBE/PRISMA/etc.), and map each item to where it will appear as you outline.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-prereg",
    title: "Pre-specify analyses to avoid HARKing",
    category: "planning",
    insight: "Lock your hypotheses and analysis plan before seeing outcome data.",
    why: "Hypothesizing After Results are Known inflates false positives and undermines confirmatory claims.",
    how: "Register the protocol and SAP (ClinicalTrials.gov, PROSPERO, OSF) before enrollment or data access; disclose any deviations.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-estimand-first",
    title: "Define the estimand before the analysis",
    category: "planning",
    insight: "State exactly what you are estimating (population, endpoint, intercurrent-event handling, summary measure) up front.",
    why: "Ambiguous estimands lead to analyses that answer a different question than intended.",
    how: "Write the estimand into the SAP using the ICH E9(R1) framework before choosing the statistical model.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-feasibility-pilot",
    title: "Run a small feasibility check first",
    category: "planning",
    insight: "Pilot recruitment, instruments, and data flow before committing the full study.",
    why: "Discovering an unworkable instrument or recruitment rate mid-study is far costlier than a pilot.",
    how: "Test the protocol on a handful of participants/records, refine, then freeze before the main study.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-power-on-primary",
    title: "Power the study on the primary outcome",
    category: "planning",
    insight: "Base the sample size on the one primary outcome, not on a convenient secondary.",
    why: "Underpowered primary outcomes yield inconclusive headline results no matter how clean the secondaries look.",
    how: "Compute n from the primary outcome's expected effect, alpha, and power, then inflate for attrition.",
    evidenceLevel: "established-practice",
  },

  // ── WRITING
  {
    id: "tip-methods-during",
    title: "Write the methods while you collect data",
    category: "writing",
    insight: "Draft methods in real time, not from memory months later.",
    why: "Procedural details, versions, and deviations are forgotten or misremembered after the fact.",
    how: "Keep a living methods document and a decision log; reconcile against the protocol at study end.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-figures-first",
    title: "Build the figures before the prose",
    category: "writing",
    insight: "Design your tables and figures first; they anchor the results narrative.",
    why: "Figures force you to decide the story; prose then explains them rather than competing with them.",
    how: "Sketch the display items, finalize them, then write results text that walks the reader through each.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-one-idea-paragraph",
    title: "One idea per paragraph, point first",
    category: "writing",
    insight: "Lead every paragraph with its single claim.",
    why: "Skimming readers (including reviewers) follow the argument from topic sentences alone.",
    how: "Start each paragraph with the claim, support it, then link forward; split paragraphs that carry two ideas.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-active-voice",
    title: "Prefer active voice and verbs over nominalizations",
    category: "writing",
    insight: "Make the actor the subject and turn noun-phrases back into verbs.",
    why: "Active, verb-driven sentences are shorter and clearer, reducing reviewer friction.",
    how: "Replace 'a comparison was made' with 'we compared'; cut hedges like 'it should be noted that'.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-old-to-new",
    title: "Chain sentences old-to-new",
    category: "writing",
    insight: "Begin each sentence with familiar information and end with the new point.",
    why: "This information flow is what readers perceive as 'good flow' and cohesion.",
    how: "Put the emphasized, new content at the end of the sentence and reuse consistent terms.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-write-abstract-last",
    title: "Write the abstract last",
    category: "writing",
    insight: "Draft the abstract after the manuscript is stable.",
    why: "The abstract must mirror the final results and conclusions, which shift during drafting.",
    how: "Once results and conclusions are fixed, distill them into the structured abstract within the word limit.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-consistent-terms",
    title: "Use one term per concept",
    category: "writing",
    insight: "Avoid elegant variation; name the same thing the same way every time.",
    why: "Synonym-swapping a key variable makes readers wonder whether you mean something different.",
    how: "Pick one label per variable/concept and use it consistently throughout.",
    evidenceLevel: "expert-opinion",
  },

  // ── STRUCTURE
  {
    id: "tip-reverse-outline",
    title: "Reverse-outline to fix structure",
    category: "structure",
    insight: "After drafting, summarize each paragraph in one line and read the skeleton.",
    why: "Structural problems are invisible at the sentence level but obvious in the one-line summary list.",
    how: "Write a margin summary per paragraph, reorder/merge/cut the list, then rewrite mismatched paragraphs.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-cars-intro",
    title: "Use the CARS four-move introduction",
    category: "structure",
    insight: "Territory -> what's known -> the gap -> your objective.",
    why: "This sequence reliably motivates the study and ends precisely at your question.",
    how: "Write one chunk per move and delete sentences that do not advance a move.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-imrad-discipline",
    title: "Keep results and interpretation separate",
    category: "structure",
    insight: "Report findings in results; reserve meaning for the discussion.",
    why: "Interpretation in results blurs the line between what you observed and what you infer.",
    how: "Move every 'this suggests' sentence from results into the discussion.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-funnel-discussion",
    title: "Invert the funnel in the discussion",
    category: "structure",
    insight: "Open the discussion narrow (your finding), then widen to implications.",
    why: "Mirroring the introduction's funnel gives the paper a satisfying, logical arc.",
    how: "Start with the principal finding, compare to literature, give mechanisms, state limitations, then implications.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-supp-offload",
    title: "Offload detail to supplements",
    category: "structure",
    insight: "Move secondary tables and procedural detail to supplementary material.",
    why: "Keeps the main text within limits and focused on the primary story without losing reproducibility detail.",
    how: "Identify content a specialist needs but the general reader does not, and relocate it with clear cross-references.",
    evidenceLevel: "expert-opinion",
  },

  // ── STATISTICS
  {
    id: "tip-effect-not-p",
    title: "Lead with effect sizes and CIs, not p-values",
    category: "statistics",
    insight: "Report magnitude and precision before the significance verdict.",
    why: "A p-value alone hides whether an effect is large, trivial, or imprecisely estimated.",
    how: "For each key result, present estimate + 95% CI + p-value, interpreted in clinical units.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-no-trend",
    title: "Do not invent 'trends toward significance'",
    category: "statistics",
    insight: "A non-significant result is non-significant; the CI describes the uncertainty.",
    why: "'Trend toward significance' is a spin device that overstates weak evidence.",
    how: "Report the estimate and CI; let the interval communicate plausible effects.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-multiplicity",
    title: "Plan for multiplicity",
    category: "statistics",
    insight: "Pre-specify how you will control error across many tests.",
    why: "Testing many endpoints and reporting the significant ones inflates false positives.",
    how: "Define the hypothesis family and a method (hierarchical, Holm, FDR) before analysis.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-dag-confounders",
    title: "Choose confounders with a DAG, not stepwise selection",
    category: "statistics",
    insight: "Select adjustment variables from a causal diagram, not by p-value.",
    why: "Stepwise selection inflates type-I error and may adjust for mediators or colliders.",
    how: "Draw a DAG, adjust only for confounders on backdoor paths, and avoid mediators/colliders.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-report-all-models",
    title: "Report every analysis you ran",
    category: "statistics",
    insight: "Disclose all models, not just the one that 'worked'.",
    why: "Selective model reporting is a core form of p-hacking.",
    how: "Present crude and adjusted estimates and label post-hoc analyses as exploratory.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-no-baseline-tests",
    title: "Do not significance-test randomized baselines",
    category: "statistics",
    insight: "Baseline p-values in a randomized trial are meaningless by design.",
    why: "Any imbalance in a properly randomized trial arose by chance, so testing it answers nothing.",
    how: "Report baseline characteristics descriptively; pre-specify adjustment for strong prognostic factors.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-calibration",
    title: "Report calibration, not just discrimination",
    category: "statistics",
    insight: "For prediction models, an AUC alone is not enough.",
    why: "A model can rank well (high AUC) yet produce poorly calibrated, misleading probabilities.",
    how: "Report calibration plots/intercept-slope alongside discrimination and validate externally.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-prespecify-margin",
    title: "Pre-specify equivalence/non-inferiority margins",
    category: "statistics",
    insight: "Decide the margin before seeing data and interpret via the CI.",
    why: "A non-significant superiority test does not prove equivalence; margins must be set a priori.",
    how: "Justify the margin clinically, power for it, and judge equivalence by whether the CI lies within it.",
    evidenceLevel: "established-practice",
  },

  // ── REPRODUCIBILITY
  {
    id: "tip-share-code",
    title: "Share code with pinned versions and seeds",
    category: "reproducibility",
    insight: "An analysis is reproducible only if dependencies and randomness are fixed.",
    why: "Unpinned packages and unset seeds change results on another machine or date.",
    how: "Pin software/package versions in a lockfile, set random seeds, and archive a snapshot with a DOI.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-fair-data",
    title: "Make data FAIR and state availability honestly",
    category: "reproducibility",
    insight: "Deposit deidentified data with a DOI rather than promising it 'on request'.",
    why: "'Available on request' statements frequently fail to yield data when tested.",
    how: "Deposit in a recognized repository with a data dictionary and license, and cite the accession.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-decision-log",
    title: "Keep a dated analytical decision log",
    category: "reproducibility",
    insight: "Record every analysis choice and deviation as it happens.",
    why: "It lets you distinguish pre-specified from post-hoc decisions and disclose deviations accurately.",
    how: "Maintain a running log with dates and rationale; surface deviations in the manuscript.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-readme-mapping",
    title: "Map scripts to manuscript outputs",
    category: "reproducibility",
    insight: "Provide a README linking each script to the table/figure it produces.",
    why: "Reviewers and reusers can reproduce a specific number without reverse-engineering the pipeline.",
    how: "Document the pipeline order and which script generates each result in the repository README.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-replicate-internally",
    title: "Have a colleague reproduce your key result",
    category: "reproducibility",
    insight: "Ask an independent colleague to regenerate the headline number from your code.",
    why: "An internal replication catches path bugs, version issues, and undocumented steps before submission.",
    how: "Hand over the repo and data; confirm they reproduce the primary result unaided.",
    evidenceLevel: "expert-opinion",
  },

  // ── LITERATURE
  {
    id: "tip-cite-primary",
    title: "Cite the primary source, not the review",
    category: "literature",
    insight: "Trace each claim to the original study before citing it.",
    why: "Citing reviews propagates errors (citation laundering) and weakens support for specific claims.",
    how: "Find the review's source for the claim, read it, and cite the primary study directly.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-read-before-cite",
    title: "Never cite a paper you have not read",
    category: "literature",
    insight: "Read the full text, not just the abstract, before citing.",
    why: "Abstracts omit caveats; citing them risks misrepresenting the source.",
    how: "Open and read the relevant section; confirm it supports your exact sentence.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-snowball",
    title: "Snowball citations to find missed work",
    category: "literature",
    insight: "Follow references backward and citing articles forward.",
    why: "Keyword searches miss seminal or differently-worded work; snowballing recovers it.",
    how: "Scan reference lists of key papers and find newer papers that cite them, then screen.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-document-search",
    title: "Save the full executable search string",
    category: "literature",
    insight: "Record the exact query and date for every database searched.",
    why: "Reproducible searches require the executable string, not just keywords (PRISMA-S).",
    how: "Copy the full query, note the platform and date, and place it in the methods/appendix.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-grey-literature",
    title: "Search grey literature to reduce publication bias",
    category: "literature",
    insight: "Include registries, preprints, and theses, not just indexed journals.",
    why: "Published studies skew positive; unpublished and registered studies balance the picture.",
    how: "Search trial registries and preprint servers, and document them like database searches.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-check-retractions",
    title: "Screen references against retraction databases",
    category: "literature",
    insight: "Verify no citation has been retracted before submission.",
    why: "Citing retracted work as valid evidence undermines your paper and can persist for years.",
    how: "Check the final list against retraction sources and confirm each DOI resolves correctly.",
    evidenceLevel: "established-practice",
  },

  // ── FIGURES
  {
    id: "tip-self-explanatory-figures",
    title: "Make figures self-explanatory",
    category: "figures",
    insight: "A reader should understand each figure from its caption alone.",
    why: "Figures are read out of order; a dependent caption forces hunting through the text.",
    how: "Write captions that state what/whom/comparison, label axes with units, and define error bars.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-honest-axes",
    title: "Keep axes and scales honest",
    category: "figures",
    insight: "Do not truncate axes or use 3D effects to exaggerate differences.",
    why: "Misleading scales overstate effects and damage credibility when noticed.",
    how: "Start bar-chart axes at zero, keep aspect ratios honest, and avoid decorative distortion.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-colorblind-safe",
    title: "Use colorblind-safe, redundant encoding",
    category: "figures",
    insight: "Do not rely on color alone, especially red/green.",
    why: "A large share of readers cannot distinguish common color pairs.",
    how: "Use colorblind-safe palettes plus redundant shapes/line styles and adequate contrast.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-numbers-at-risk",
    title: "Add numbers-at-risk to survival curves",
    category: "figures",
    insight: "Kaplan-Meier plots need a numbers-at-risk table beneath them.",
    why: "Late-time curve segments based on few patients are otherwise over-interpreted.",
    how: "Place a numbers-at-risk row under the time axis at regular intervals.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-table-or-figure",
    title: "Don't duplicate data in table and figure",
    category: "figures",
    insight: "Choose a table for exact values or a figure for patterns, not both.",
    why: "Duplication wastes the display budget and signals weak editing.",
    how: "Decide whether precision or pattern matters more and present the data once.",
    evidenceLevel: "expert-opinion",
  },

  // ── PUBLISHING
  {
    id: "tip-scope-fit",
    title: "Match the manuscript to journal scope, not impact factor",
    category: "publishing",
    insight: "Fit with scope and readership predicts acceptance better than prestige chasing.",
    why: "Out-of-scope submissions are desk-rejected regardless of quality.",
    how: "Read the aims/scope and recent issues; submit where similar work is published.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-cover-letter",
    title: "Sell the fit in the cover letter",
    category: "publishing",
    insight: "Use three short paragraphs to argue fit, not to restate the abstract.",
    why: "Editors triage on relevance; the letter is your chance to make that case.",
    how: "State the key finding, why it fits this journal, and confirm originality and ethics.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-register-and-report",
    title: "Publish negative and null results",
    category: "publishing",
    insight: "Report registered studies even when the primary outcome is null.",
    why: "Non-publication of null results is a major source of publication bias.",
    how: "Frame the null result's value, post registry results on time, and submit it for publication.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-handle-rejection",
    title: "Mine rejections for value",
    category: "publishing",
    insight: "Address legitimate reviewer concerns before resubmitting elsewhere.",
    why: "The same weaknesses will resurface at the next journal if left unfixed.",
    how: "Separate scope rejection from substance rejection, fix real issues, and reformat for the next target.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-presub-checklist",
    title: "Run a pre-submission checklist",
    category: "publishing",
    insight: "Verify every required statement and limit before submitting.",
    why: "Missing ethics/registration/COI statements or exceeding limits triggers desk returns.",
    how: "Check the reporting checklist, all statements, displays, supplements, and word/reference limits.",
    evidenceLevel: "established-practice",
  },

  // ── REVISION
  {
    id: "tip-point-by-point",
    title: "Answer reviewers point by point",
    category: "revision",
    insight: "Quote each comment, respond, and show the exact revised text and location.",
    why: "Editors verify changes quickly when each comment maps to a concrete edit.",
    how: "Restate the comment, give your response, paste the new text, and cite the page/line.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-change-summary",
    title: "Open the response with a change summary",
    category: "revision",
    insight: "Give the editor a 3-5 item overview before the detailed responses.",
    why: "It orients the editor and frames the revision as substantial and responsive.",
    how: "List the major changes and any new analyses, then proceed point by point.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-disagree-with-evidence",
    title: "Disagree with evidence, not attitude",
    category: "revision",
    insight: "Push back on incorrect requests respectfully and with citations.",
    why: "A defensible, courteous rebuttal keeps the editor on your side; a dismissive one loses them.",
    how: "Acknowledge the concern, present evidence, offer a partial accommodation, and defer to the editor.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-address-editor",
    title: "Answer the editor's asks, not just reviewers'",
    category: "revision",
    insight: "Decision letters contain editorial requests separate from reviewer comments.",
    why: "Missing a required policy item (data sharing, checklist) stalls or sinks the revision.",
    how: "Separate the editor's requests, address each explicitly, and confirm compliance.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-recheck-consistency",
    title: "Re-read the whole paper after edits",
    category: "revision",
    insight: "Revisions create inconsistencies between sections.",
    why: "A changed result must propagate to the abstract, tables, figures, and conclusion.",
    how: "After edits, read end-to-end to ensure numbers and claims agree everywhere.",
    evidenceLevel: "expert-opinion",
  },

  // ── ETHICS
  {
    id: "tip-authorship-icmje",
    title: "Apply ICMJE authorship criteria early",
    category: "ethics",
    insight: "Agree authorship against the four criteria before writing, not after.",
    why: "Late authorship disputes are common and damaging; early agreement prevents them.",
    how: "Use the four ICMJE criteria plus a CRediT statement; acknowledge non-qualifying contributors.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-disclose-coi",
    title: "Over-disclose conflicts of interest",
    category: "ethics",
    insight: "When in doubt, disclose financial and non-financial conflicts.",
    why: "Undisclosed conflicts discovered later cause corrections and reputational harm.",
    how: "Complete the ICMJE disclosure for all authors and state the funder's role.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-deidentify",
    title: "Deidentify rigorously before sharing",
    category: "ethics",
    insight: "Remove identifiers and risky quasi-identifier combinations.",
    why: "Rare detail combinations can re-identify individuals even without direct identifiers.",
    how: "Strip identifiers, blur identifiable images (or consent), and follow HIPAA/GDPR and consent terms.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-no-text-recycling",
    title: "Disclose any text reuse, including your own",
    category: "ethics",
    insight: "Reusing your prior text verbatim is self-plagiarism unless disclosed.",
    why: "Editors expect original text; undisclosed overlap can trigger a misconduct inquiry.",
    how: "Paraphrase and cite, disclose legitimate methods overlap, and run a similarity check.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-ai-disclosure",
    title: "Disclose AI assistance and verify its output",
    category: "ethics",
    insight: "AI tools cannot be authors and their output must be checked.",
    why: "AI can fabricate citations and numbers; you remain accountable for accuracy.",
    how: "Follow the journal's AI policy, disclose use, and verify every fact and reference yourself.",
    evidenceLevel: "established-practice",
  },

  // ── PRODUCTIVITY
  {
    id: "tip-outline-first",
    title: "Draft from a one-page outline",
    category: "productivity",
    insight: "Settle the structure as bullets before writing prose.",
    why: "Fixing structure in prose is slow; fixing it in an outline is fast.",
    how: "List headings and key bullets, sequence figures, then expand only once the skeleton holds.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-anticipate-reviewers",
    title: "Pre-empt likely reviewer objections",
    category: "productivity",
    insight: "Address foreseeable weaknesses before reviewers raise them.",
    why: "Proactively handled limitations save a revision round and build trust.",
    how: "List probable objections, address them in methods/limitations, and add answering sensitivity analyses.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-single-source-of-truth",
    title: "Keep one source of truth for the manuscript",
    category: "productivity",
    insight: "Avoid divergent copies emailed among co-authors.",
    why: "Multiple versions cause lost edits and conflicting final files.",
    how: "Agree one shared document, assign sections, resolve comments in rounds, and freeze before submission.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-reference-manager",
    title: "Cite-while-you-write with a reference manager",
    category: "productivity",
    insight: "Manage references in a tool, not by hand.",
    why: "Manual citation numbering breaks on every edit and introduces formatting errors.",
    how: "Import verified metadata, deduplicate, cite with a journal CSL style, and audit the final list.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-write-daily",
    title: "Write in short, regular sessions",
    category: "productivity",
    insight: "Frequent short writing beats rare marathons.",
    why: "Regular sessions maintain momentum and reduce the activation cost of restarting.",
    how: "Schedule brief daily writing blocks with a concrete goal for each.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-template-prompts",
    title: "Reuse vetted prompt and section templates",
    category: "productivity",
    insight: "Keep a library of reusable templates for recurring tasks.",
    why: "Templates encode best practice and avoid reinventing structure each time.",
    how: "Maintain prompt/section templates (intro, methods, response letter) and adapt per project.",
    evidenceLevel: "expert-opinion",
  },

  // ── ORIGINALITY / SIGNIFICANCE
  {
    id: "tip-sharp-gap",
    title: "Sharpen the gap to sharpen the contribution",
    category: "originality",
    insight: "A specific, defensible gap makes the contribution self-evident.",
    why: "Vague gaps ('little is known') signal an undifferentiated study.",
    how: "Name the exact population/exposure/outcome that is unresolved and why closing it matters.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-claim-proportionate",
    title: "Keep claims proportional to the design",
    category: "originality",
    insight: "Match the strength of your claims to what the design can support.",
    why: "Overclaiming (causation from observation, novelty without evidence) invites rejection.",
    how: "Use associative language for observational data and avoid 'first/novel' without a duplicate-risk check.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-novelty-check",
    title: "Verify novelty before claiming it",
    category: "originality",
    insight: "Run a duplicate/overlap check before asserting your work is first.",
    why: "Unverified novelty claims are easily refuted and erode credibility.",
    how: "Search broadly (including grey literature) and only claim novelty the evidence supports.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-clinical-significance",
    title: "Argue clinical, not just statistical, significance",
    category: "originality",
    insight: "Show the effect is large enough to matter, not merely non-random.",
    why: "Significance without a meaningful effect size does not advance practice.",
    how: "Compare the effect to a minimal clinically important difference and state the practical implication.",
    evidenceLevel: "established-practice",
  },
  {
    id: "tip-framework-link",
    title: "Anchor the study in a framework you actually use",
    category: "originality",
    insight: "A conceptual framework should justify variables and reappear in the discussion.",
    why: "A named-but-unused framework adds nothing; an applied one strengthens coherence and significance.",
    how: "Choose the framework that predicts your relationship, justify variables with it, and interpret findings through it.",
    evidenceLevel: "expert-opinion",
  },
  {
    id: "tip-replicate-or-extend",
    title: "Position as replication or extension explicitly",
    category: "originality",
    insight: "State clearly whether you confirm, extend, or challenge prior work.",
    why: "An explicit relationship to the literature clarifies your contribution's significance.",
    how: "Name the closest prior work and articulate exactly what your study adds or contests.",
    evidenceLevel: "expert-opinion",
  },
];

export function tipsByCategory(): Record<TipCategory, ResearchTip[]> {
  const map = {} as Record<TipCategory, ResearchTip[]>;
  for (const tip of researchTips) {
    (map[tip.category] ||= []).push(tip);
  }
  return map;
}
