import type { ProjectState, ReferenceVerification } from "./types";

export function projectToMarkdown(p: ProjectState): string {
  const lines: string[] = [];
  const title = p.titleFinal || p.titleInputs.draftTitle || "(untitled)";
  lines.push(`# ${title}`, "");

  if (p.researchTypeResult) {
    lines.push("> **Research type:** " + p.researchTypeResult.primaryGuidelineName);
    if (p.researchTypeResult.possibleExtensionIds.length) {
      lines.push("> **Possible extensions:** " + p.researchTypeResult.possibleExtensionIds.join(", "));
    }
    lines.push("");
  }

  const sect = (h: string, body: string) => {
    lines.push(`# ${h}`, "", body?.trim() ? body : "_(not yet written)_", "");
  };

  sect("Introduction", p.sections.introduction);
  sect("Methods", p.sections.methods);
  sect("Results", p.sections.results);
  sect("Discussion", p.sections.discussion);
  sect("Conclusion", p.sections.conclusion);

  lines.push("# References", "");
  if (p.references.verifications.length === 0) {
    lines.push("_(no references added)_", "");
  } else {
    p.references.verifications.forEach((v, i) => {
      lines.push(`${i + 1}. ${v.correctedCitationVancouver || v.originalText}`);
    });
    lines.push("");
  }

  // Compliance overview
  if (p.researchTypeResult) {
    lines.push("# Reporting Guideline Compliance", "");
    lines.push(`Primary: **${p.researchTypeResult.primaryGuidelineName}**`);
    if (p.researchTypeResult.possibleExtensionIds.length) {
      lines.push(`Extensions: ${p.researchTypeResult.possibleExtensionIds.join(", ")}`);
    }
    lines.push("");
    for (const [section, checklist] of Object.entries(p.researchTypeResult.sectionChecklists || {})) {
      lines.push(`## ${section[0].toUpperCase() + section.slice(1)}`);
      for (const c of checklist as string[]) lines.push(`- [ ] ${c}`);
      lines.push("");
    }
  }

  // Novelty
  if (p.noveltyReport) {
    lines.push("# Novelty / Similarity Report", "");
    lines.push(`**Risk:** ${p.noveltyReport.risk.replaceAll("_", " ")}`);
    if (p.noveltyReport.exactMatches.length) {
      lines.push("", "**Exact / near-exact matches:**");
      for (const m of p.noveltyReport.exactMatches) {
        lines.push(`- ${m.title} (${m.year || "n/a"}) — ${m.url || ""}`);
      }
    }
    if (p.noveltyReport.similar.length) {
      lines.push("", "**Similar studies:**");
      for (const m of p.noveltyReport.similar) {
        lines.push(`- ${m.title} (${m.year || "n/a"}) — ${m.url || ""}`);
      }
    }
    lines.push("", `_Disclaimer:_ ${p.noveltyReport.disclaimer}`, "");
  }

  // Reference verification
  if (p.references.verifications.length) {
    lines.push("# Reference Verification Report", "");
    lines.push("| # | Title | PubMed | DOI | Match | Confidence | Problems |");
    lines.push("|---|-------|--------|-----|-------|-----------|----------|");
    p.references.verifications.forEach((v, i) => {
      const pm = v.pubmed?.pmid ? `PMID ${v.pubmed.pmid}` : v.checks.pubmedIndexed === false ? "not found" : "unknown";
      const doi = v.crossref?.doi || v.pubmed?.doi || v.parsed.doi || "—";
      const problems = v.problems.join("; ").replace(/\|/g, "/");
      lines.push(
        `| ${i + 1} | ${cleanCell(v.parsed.title || v.originalText.slice(0, 80))} | ${pm} | ${doi} | ${v.checks.metadataMatch} | ${v.confidence} | ${problems} |`
      );
    });
    lines.push("");
  }

  lines.push("---", `_Generated by MedCore Research Builder on ${new Date().toISOString().slice(0, 10)}._`);
  return lines.join("\n");
}

function cleanCell(s: string) {
  return s.replace(/\|/g, "/").replace(/\n+/g, " ").trim();
}

export function referencesToCSV(verifs: ReferenceVerification[]): string {
  const header = [
    "index",
    "title",
    "authors",
    "journal",
    "year",
    "doi",
    "pmid",
    "pubmedIndexed",
    "doiResolved",
    "metadataMatch",
    "duplicate",
    "retractionOrConcern",
    "confidence",
    "problems",
    "correctedCitation",
    "originalText",
  ];
  const lines = [header.join(",")];
  verifs.forEach((v, i) => {
    const row = [
      String(i + 1),
      v.pubmed?.title || v.crossref?.title || v.parsed.title || "",
      (v.pubmed?.authors || v.crossref?.authors || v.parsed.authors || []).join("; "),
      v.pubmed?.journal || v.crossref?.journal || v.parsed.journal || "",
      v.pubmed?.year || v.crossref?.year || v.parsed.year || "",
      v.pubmed?.doi || v.crossref?.doi || v.parsed.doi || "",
      v.pubmed?.pmid || v.parsed.pmid || "",
      String(v.checks.pubmedIndexed),
      String(v.checks.doiResolved),
      v.checks.metadataMatch,
      String(v.checks.duplicate),
      String(v.checks.possibleRetractionOrConcern),
      v.confidence,
      v.problems.join(" | "),
      v.correctedCitationVancouver || "",
      v.originalText,
    ];
    lines.push(row.map(csvEscape).join(","));
  });
  return lines.join("\n");
}

function csvEscape(s: string): string {
  if (s == null) return "";
  const needs = /[",\n]/.test(s);
  if (!needs) return s;
  return `"${s.replace(/"/g, '""')}"`;
}

export function complianceToMarkdown(p: ProjectState): string {
  const lines: string[] = [];
  lines.push("# Reporting Guideline Compliance Report", "");
  if (!p.researchTypeResult) {
    lines.push("_No reporting guideline selected._");
    return lines.join("\n");
  }
  lines.push(`**Primary guideline:** ${p.researchTypeResult.primaryGuidelineName}`);
  if (p.researchTypeResult.possibleExtensionIds.length) {
    lines.push(`**Extensions:** ${p.researchTypeResult.possibleExtensionIds.join(", ")}`);
  }
  lines.push("");
  for (const [section, items] of Object.entries(p.researchTypeResult.sectionChecklists || {})) {
    const fb = p.sectionFeedback[section as keyof typeof p.sectionFeedback];
    lines.push(`## ${section[0].toUpperCase() + section.slice(1)}`);
    if (fb) {
      for (const c of fb.checklistCoverage) {
        const mark = c.status === "covered" ? "✅" : c.status === "partial" ? "⚠️" : "❌";
        lines.push(`- ${mark} ${c.item}${c.comment ? " — " + c.comment : ""}`);
      }
      if (fb.missingInformation.length) {
        lines.push("", "**Missing information:**");
        for (const m of fb.missingInformation) lines.push(`- ${m}`);
      }
      if (fb.riskWarnings.length) {
        lines.push("", "**Risk warnings:**");
        for (const m of fb.riskWarnings) lines.push(`- ${m}`);
      }
    } else {
      for (const c of items as string[]) lines.push(`- [ ] ${c}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
