import type { Guideline } from "./types";

/**
 * Curated EQUATOR-based guideline registry.
 * Checklist prompts are paraphrased compliance reminders, not verbatim
 * copies of copyrighted checklists. For full checklist text always
 * refer to the linked official source.
 */
export const guidelines: Guideline[] = [
  {
    id: "consort-2025",
    name: "CONSORT 2025 — Randomized Trials",
    acronym: "CONSORT",
    // CONSORT 2025 was published 14 Apr 2025 simultaneously in BMJ, JAMA,
    // The Lancet, Nature Medicine, and PLOS Medicine, superseding CONSORT 2010.
    versionOrYear: "2025 (published; supersedes 2010)",
    source: "EQUATOR",
    officialUrl: "https://www.consort-spirit.org/",
    appliesTo: ["randomized controlled trial", "RCT", "parallel-group trial"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: [
        "Identify the study as a randomized trial in the title.",
      ],
      introduction: [
        "Provide scientific background and rationale.",
        "State specific objectives or hypotheses.",
      ],
      methods: [
        "Describe trial design (parallel, factorial, cluster, etc.) including allocation ratio.",
        "Describe eligibility criteria and settings.",
        "Detail the interventions for each group with sufficient replicability.",
        "Pre-specify primary and secondary outcomes.",
        "Report sample size determination including assumptions.",
        "Describe randomization method, allocation concealment, and implementation.",
        "Describe blinding (participants, providers, outcome assessors).",
        "Specify statistical methods including handling of missing data and subgroup/adjusted analyses.",
        "State trial registration number and protocol availability.",
      ],
      results: [
        "Provide a participant flow diagram (CONSORT flow).",
        "Report dates of recruitment and follow-up.",
        "Show baseline demographic and clinical characteristics by group.",
        "Report numbers analyzed per group (ITT vs. per-protocol).",
        "Report outcomes with effect size and precision (e.g., 95% CI).",
        "Report all important harms or unintended effects per group.",
      ],
      discussion: [
        "Discuss limitations including sources of potential bias and imprecision.",
        "Discuss generalizability (external validity).",
        "Provide interpretation consistent with results, balancing benefits and harms.",
      ],
      conclusion: [
        "Avoid overstating efficacy; align conclusion with the primary outcome and trial design.",
      ],
    },
    extensions: [
      "CONSORT-Cluster",
      "CONSORT-Non-inferiority/Equivalence",
      "CONSORT-Pragmatic",
      "CONSORT-Pilot/Feasibility",
      "CONSORT-Abstracts",
      "CONSORT-Harms",
      "CONSORT-NPT (non-pharmacologic treatments)",
      "CONSORT-AI",
      "CONSORT-eHealth",
    ],
  },
  {
    id: "strobe",
    name: "STROBE — Observational Studies",
    acronym: "STROBE",
    versionOrYear: "2007",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/strobe/",
    appliesTo: ["cohort", "case-control", "cross-sectional", "observational"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: [
        "Indicate the study design (cohort, case-control, cross-sectional) in the title or abstract.",
      ],
      introduction: [
        "Describe scientific background and rationale.",
        "State pre-specified objectives, including any hypotheses.",
      ],
      methods: [
        "Describe study design clearly.",
        "Describe setting, locations, and relevant dates.",
        "State eligibility criteria and sources/methods of selection.",
        "Define exposures, outcomes, predictors, potential confounders, effect modifiers.",
        "Describe data sources and measurement; address comparability of methods.",
        "Describe efforts to address potential sources of bias.",
        "Explain how study size was arrived at.",
        "Describe handling of quantitative variables and any grouping.",
        "Describe statistical methods including how confounding was addressed, subgroups, missing data, sensitivity analyses.",
      ],
      results: [
        "Report numbers at each stage (eligible, examined, included, completed follow-up).",
        "Give characteristics of participants and information on exposures and outcomes.",
        "Report unadjusted and confounder-adjusted estimates with precision.",
        "Report category boundaries for continuous variables when categorized.",
      ],
      discussion: [
        "Summarize key results.",
        "Discuss limitations including sources of potential bias or imprecision.",
        "Provide cautious interpretation considering objectives, limitations, multiplicity, and similar studies.",
        "Discuss generalizability.",
      ],
      conclusion: [
        "Avoid causal language unsupported by an observational design.",
      ],
    },
    extensions: [
      "RECORD (routinely collected health data)",
      "RECORD-PE (pharmacoepidemiology)",
      "STROBE-ME (molecular epidemiology)",
      "STROBE-nut",
      "STROBE-equity",
    ],
  },
  {
    id: "prisma-2020",
    name: "PRISMA 2020 — Systematic Reviews & Meta-analyses",
    acronym: "PRISMA",
    versionOrYear: "2020",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/prisma/",
    appliesTo: ["systematic review", "meta-analysis"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: [
        "Identify the report as a systematic review (and meta-analysis if applicable).",
      ],
      introduction: [
        "Describe rationale in the context of existing knowledge.",
        "Provide an explicit statement of objective(s) or question(s) using a structured framework (e.g., PICO).",
      ],
      methods: [
        "Specify the inclusion and exclusion criteria.",
        "Specify all information sources and date last searched.",
        "Provide the full search strategies for all databases.",
        "Describe selection, data collection, and data items processes.",
        "Describe methods for assessing risk of bias of included studies.",
        "Describe synthesis methods, including any meta-analytic, heterogeneity, or certainty-of-evidence (e.g., GRADE) approach.",
        "State whether a protocol was prepared and registered (e.g., PROSPERO).",
      ],
      results: [
        "Provide a PRISMA 2020 flow diagram.",
        "Cite included studies and present their characteristics.",
        "Present risk-of-bias assessments.",
        "Present synthesis results (individual study results and combined estimates if applicable).",
        "Report certainty of evidence for each main outcome.",
      ],
      discussion: [
        "Provide a general interpretation in the context of other evidence.",
        "Discuss limitations of the evidence and the review process.",
        "Discuss implications for practice, policy, and future research.",
      ],
      conclusion: [
        "Align conclusion with strength of evidence and risk-of-bias findings.",
      ],
    },
    extensions: [
      "PRISMA-P (protocols)",
      "PRISMA-ScR (scoping reviews)",
      "PRISMA-DTA (diagnostic test accuracy)",
      "PRISMA-NMA (network meta-analyses)",
      "PRISMA-IPD (individual participant data)",
      "PRISMA-Harms",
      "PRISMA for overviews of reviews",
    ],
  },
  {
    id: "spirit",
    name: "SPIRIT — Clinical Trial Protocols",
    acronym: "SPIRIT",
    // SPIRIT 2025 was co-published with CONSORT 2025 (Apr 2025).
    versionOrYear: "2025 (published; supersedes 2013)",
    source: "EQUATOR",
    officialUrl: "https://www.consort-spirit.org/",
    appliesTo: ["clinical trial protocol", "RCT protocol"],
    manuscriptSections: ["title", "introduction", "methods", "references"],
    checklistPrompts: {
      title: ["Identify the document as a clinical trial protocol."],
      introduction: ["Provide background and rationale.", "Pre-specify objectives and hypotheses."],
      methods: [
        "Describe trial design (allocation ratio, framework).",
        "Specify study setting, eligibility criteria, interventions.",
        "Pre-specify outcomes and analysis plan.",
        "Describe randomization, allocation concealment, blinding plans.",
        "Plan for sample size justification, recruitment, statistical methods, data management.",
        "Describe ethics, consent, confidentiality, and dissemination plans.",
        "State trial registration plan (e.g., ClinicalTrials.gov, ISRCTN).",
      ],
    },
  },
  {
    id: "prisma-p",
    name: "PRISMA-P — Systematic Review Protocols",
    acronym: "PRISMA-P",
    versionOrYear: "2015",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/prisma-protocols/",
    appliesTo: ["systematic review protocol"],
    manuscriptSections: ["title", "introduction", "methods", "references"],
    checklistPrompts: {
      title: ["Identify the document as a systematic review or meta-analysis protocol."],
      introduction: ["State rationale and objectives in a structured (e.g., PICO) format."],
      methods: [
        "Describe eligibility criteria, information sources, draft search strategy.",
        "Describe planned study selection, data extraction, risk of bias, and synthesis methods.",
        "State plan for registration (e.g., PROSPERO).",
      ],
    },
  },
  {
    id: "stard",
    name: "STARD — Diagnostic Accuracy Studies",
    acronym: "STARD",
    versionOrYear: "2015",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/stard/",
    appliesTo: ["diagnostic accuracy"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: ["Identify the study as a diagnostic accuracy study and name the index test."],
      introduction: ["State scientific and clinical background and study objectives."],
      methods: [
        "Define the index test and reference standard, including thresholds.",
        "Describe participant selection, sampling, and setting.",
        "Describe blinding of index-test readers to reference standard and vice versa.",
        "Describe flow and timing between the index test and reference standard.",
        "Pre-specify statistical methods for accuracy estimates (sensitivity, specificity, predictive values, ROC/AUC).",
        "Describe handling of indeterminate, missing, or outliers.",
      ],
      results: [
        "Show flow diagram of participants.",
        "Report cross-tabulation between index test and reference standard.",
        "Report estimates of diagnostic accuracy with precision (95% CI).",
        "Report adverse events from the index or reference test.",
      ],
      discussion: [
        "Discuss clinical applicability and study limitations including spectrum and verification bias.",
      ],
      conclusion: ["Align clinical implications with study population and reference standard."],
    },
  },
  {
    id: "tripod",
    name: "TRIPOD — Prognostic / Prediction Model Studies",
    acronym: "TRIPOD",
    versionOrYear: "2015 (TRIPOD+AI 2024 extension exists)",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/tripod-statement/",
    appliesTo: ["prediction model", "prognostic model", "diagnostic model"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: ["Identify the study as developing and/or validating a multivariable prediction model."],
      introduction: ["State the prediction problem, intended use, and target population."],
      methods: [
        "Describe study design, data sources, and participants.",
        "Define outcome and how/when it was measured; blinding of outcome to predictors.",
        "Describe candidate predictors and how/when they were measured.",
        "Describe sample size and handling of missing data.",
        "Describe modelling approach, predictor selection, and handling of continuous predictors.",
        "Describe model performance measures (discrimination, calibration) and validation plan (internal/external).",
      ],
      results: [
        "Report flow of participants and characteristics.",
        "Report model coefficients/equations and performance with CI.",
        "Report calibration and discrimination with appropriate plots/statistics.",
      ],
      discussion: [
        "Discuss limitations (overfitting, generalisability, missing data).",
        "Discuss clinical use, implementation, and need for external validation.",
      ],
      conclusion: ["Avoid claims of clinical utility without external validation evidence."],
    },
    extensions: ["TRIPOD+AI (2024)"],
  },
  {
    id: "care",
    name: "CARE — Case Reports",
    acronym: "CARE",
    versionOrYear: "2013 (updated)",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/care/",
    appliesTo: ["case report", "case series (small)"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: ["Use the word 'case report' and indicate the area of interest in the title."],
      introduction: ["Provide background of the condition and relevance of the case."],
      methods: [
        "Provide patient information (de-identified demographics, history, relevant comorbidities).",
        "Describe clinical findings.",
        "Describe timeline of events.",
        "Describe diagnostic assessment (tests, challenges, reasoning).",
        "Describe therapeutic intervention (type, dosage, duration, changes).",
        "Describe follow-up and outcomes including adverse and unanticipated events.",
        "Document informed consent obtained from the patient.",
      ],
      results: [
        "Present the case timeline and outcomes objectively without overgeneralization.",
      ],
      discussion: [
        "Discuss strengths and limitations, relevant medical literature, and lessons learned.",
      ],
      conclusion: ["Provide a take-away message proportional to a single case (not generalisable)."],
    },
  },
  {
    id: "agree-right",
    name: "AGREE / RIGHT — Clinical Practice Guidelines",
    acronym: "AGREE/RIGHT",
    versionOrYear: "AGREE II, RIGHT 2017",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/right-statement/",
    appliesTo: ["clinical practice guideline"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: ["Identify the document as a clinical practice guideline."],
      introduction: ["State purpose, scope, population, and target users."],
      methods: [
        "Describe panel composition and management of conflicts of interest.",
        "Describe evidence-review methods and grading system (e.g., GRADE).",
        "Describe formulation, voting, and review of recommendations.",
        "Describe external peer review and updating plan.",
      ],
      results: [
        "Present each recommendation with strength and evidence certainty.",
        "Provide rationale and supporting evidence summaries.",
      ],
      discussion: [
        "Discuss applicability, implementation, monitoring, and equity considerations.",
      ],
      conclusion: ["Summarize key recommendations with appropriate uncertainty acknowledgement."],
    },
  },
  {
    id: "srqr-coreq",
    name: "SRQR / COREQ — Qualitative Research",
    acronym: "SRQR/COREQ",
    versionOrYear: "2014 / 2007",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/srqr/",
    appliesTo: ["qualitative", "interviews", "focus groups"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: ["Identify the study as qualitative and indicate the methodology."],
      introduction: ["State the problem, research question, and theoretical framework."],
      methods: [
        "Describe research paradigm/orientation and reflexivity of researchers.",
        "Describe context, sampling strategy, and participant recruitment.",
        "Describe data collection (interviews, focus groups, observation) and procedures.",
        "Describe analysis approach, coding, and how trustworthiness was ensured (e.g., triangulation, member checking).",
        "Describe ethics approval and informed consent.",
      ],
      results: [
        "Report themes/findings with illustrative quotations and participant context.",
      ],
      discussion: [
        "Discuss findings in relation to the literature, reflexivity, and transferability.",
      ],
      conclusion: ["Avoid quantitative generalisation; emphasize transferability and meaning."],
    },
  },
  {
    id: "arrive",
    name: "ARRIVE 2.0 — Animal / Pre-clinical Studies",
    acronym: "ARRIVE",
    versionOrYear: "2.0 (2020)",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/improving-bioscience-research-reporting-the-arrive-guidelines-for-reporting-animal-research/",
    appliesTo: ["animal", "preclinical", "in vivo"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: ["Indicate the species and main intervention/measure in the title or abstract."],
      introduction: ["State background and objectives, including translational relevance."],
      methods: [
        "Describe species, strain, sex, age, source, and welfare-related housing/husbandry.",
        "Describe experimental design including randomization, blinding, and sample size justification.",
        "Pre-specify outcomes and statistical methods.",
        "Describe ethics approval and the 3Rs (Replacement, Reduction, Refinement).",
      ],
      results: [
        "Report numbers of animals at each stage, including exclusions and reasons.",
        "Report outcomes with appropriate effect sizes and precision.",
      ],
      discussion: [
        "Discuss limitations, generalisability to humans, and translational caveats.",
      ],
      conclusion: ["Avoid premature clinical extrapolation from animal data."],
    },
  },
  {
    id: "squire",
    name: "SQUIRE — Quality Improvement",
    acronym: "SQUIRE",
    versionOrYear: "2.0 (2015)",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/squire/",
    appliesTo: ["quality improvement"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: ["Indicate the project as a quality-improvement initiative."],
      introduction: ["Describe nature and significance of the local problem and aim."],
      methods: [
        "Describe context (setting, factors thought to affect success).",
        "Describe the intervention(s) and improvement theory/rationale.",
        "Describe study of intervention (timing, evolution, comparison group).",
        "Describe measures (process, outcome, balancing).",
        "Describe analysis approach and ethical considerations.",
      ],
      results: [
        "Show initial steps of the intervention and their evolution over time, including unintended consequences.",
        "Report quantitative and qualitative data on processes, outcomes, and contextual factors.",
      ],
      discussion: [
        "Discuss key findings, lessons, limitations, sustainability, and spread.",
      ],
      conclusion: ["Avoid overstating causal effect of complex improvement interventions."],
    },
  },
  {
    id: "cheers",
    name: "CHEERS — Economic Evaluations",
    acronym: "CHEERS",
    versionOrYear: "2022",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/cheers/",
    appliesTo: ["economic evaluation", "cost-effectiveness", "cost-utility"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: ["Identify the study as an economic evaluation and the comparators."],
      introduction: [
        "State the question, target population, setting, and decision context.",
        "State perspective(s) (payer, societal, etc.).",
      ],
      methods: [
        "Describe comparators, time horizon, discount rate, choice of outcome.",
        "Describe how effectiveness was estimated (trial, model, review).",
        "Describe measurement and valuation of costs and outcomes.",
        "Describe currency, price date, conversion if any, and model assumptions.",
        "Describe analytical methods including sensitivity/uncertainty analyses.",
      ],
      results: [
        "Report study parameters and base-case results with incremental costs, outcomes, and ratios (ICERs).",
        "Characterize uncertainty (e.g., probabilistic sensitivity analysis).",
        "Report disaggregated costs and outcomes where feasible.",
      ],
      discussion: [
        "Discuss generalisability, limitations, equity considerations, and policy implications.",
      ],
      conclusion: ["Tie cost-effectiveness statement to the chosen perspective and threshold."],
    },
  },
  {
    id: "gramms",
    name: "GRAMMS — Mixed-Methods Research",
    acronym: "GRAMMS",
    versionOrYear: "2008",
    source: "EQUATOR",
    officialUrl: "https://www.equator-network.org/?post_type=eq_guidelines&eq_guidelines_study_design=mixed-methods-studies",
    appliesTo: ["mixed methods"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      title: ["State the study uses a mixed-methods design."],
      introduction: ["Provide rationale for combining qualitative and quantitative methods."],
      methods: [
        "Describe each component's design and how/when they are integrated (concurrent, sequential).",
        "Describe sampling, data collection, and analysis for each strand.",
        "Apply relevant single-method guidelines (CONSORT/STROBE for quant; SRQR/COREQ for qual).",
      ],
      results: [
        "Report quantitative and qualitative findings separately and the integration meta-inferences.",
      ],
      discussion: [
        "Discuss what integration added beyond single-method findings.",
        "Discuss limitations specific to mixed-methods integration.",
      ],
      conclusion: ["Frame conclusions in terms of integrated insights, not just one strand."],
    },
  },
  {
    id: "custom",
    name: "Custom — Other / Manual Guideline",
    acronym: "CUSTOM",
    source: "Custom",
    officialUrl: "https://www.equator-network.org/reporting-guidelines/",
    appliesTo: ["other", "custom"],
    manuscriptSections: [
      "title",
      "abstract",
      "introduction",
      "methods",
      "results",
      "discussion",
      "conclusion",
    ],
    checklistPrompts: {
      methods: ["Describe methods completely enough for replication."],
      results: ["Report results aligned with pre-specified objectives."],
      discussion: ["Interpret results without overstating beyond the design's capability."],
    },
    notes:
      "Use this entry when no specific EQUATOR guideline fits, or to add a custom checklist.",
  },
];

export const guidelineById = (id: string) =>
  guidelines.find((g) => g.id === id);

export const allManuscriptSections: Array<
  "introduction" | "methods" | "results" | "discussion" | "conclusion"
> = ["introduction", "methods", "results", "discussion", "conclusion"];
