import type { JournalSpec, ManuscriptTypeSpec } from "../types";

/* ============================================================
   Reusable manuscript-type defaults to keep entries small.
   ============================================================ */

const ORIG_3000: ManuscriptTypeSpec = {
  type: "original_investigation",
  mainTextWordLimit: 3000,
  abstractWordLimit: 350,
  referencesMax: 50,
  displayItemsMax: 5,
  keywordsMin: 3,
  keywordsMax: 8,
  keyPointsRequired: false,
};

const ORIG_4500: ManuscriptTypeSpec = { ...ORIG_3000, mainTextWordLimit: 4500, referencesMax: 75 };

const BRIEF_REPORT: ManuscriptTypeSpec = {
  type: "brief_report",
  mainTextWordLimit: 1500,
  abstractWordLimit: 250,
  referencesMax: 20,
  displayItemsMax: 2,
};

const CASE_REPORT: ManuscriptTypeSpec = {
  type: "case_report",
  mainTextWordLimit: 1200,
  abstractWordLimit: 150,
  referencesMax: 15,
  displayItemsMax: 4,
};

const SYSTEMATIC_REVIEW: ManuscriptTypeSpec = {
  type: "systematic_review",
  mainTextWordLimit: 5000,
  abstractWordLimit: 350,
  referencesMax: 100,
  displayItemsMax: 6,
};

const PROTOCOL: ManuscriptTypeSpec = {
  type: "protocol",
  mainTextWordLimit: 4000,
  abstractWordLimit: 350,
  referencesMax: 40,
  displayItemsMax: 5,
};

/* ============================================================
   Standard ICMJE-conformant requirement set (most major journals).
   ============================================================ */

const ICMJE_FULL = {
  icmjeAuthorship: true,
  ppiStatement: false,
  dataSharingStatement: true,
  fundingStatement: true,
  coiStatement: true,
  creditTaxonomy: true,
  registrationStatement: true,
  aiDisclosure: true, // ICMJE 2026
  ethicsStatement: true,
  consentStatement: true,
};

/* ============================================================
   Tier A — fully encoded journals
   ============================================================ */

export const journals: JournalSpec[] = [
  {
    id: "bmj",
    name: "The BMJ",
    publisher: "BMJ Publishing Group",
    homepage: "https://www.bmj.com/",
    authorGuideUrl: "https://www.bmj.com/about-bmj/resources-authors/article-types/research",
    reviewerGuideUrl: "https://www.bmj.com/about-bmj/resources-reviewers",
    editorGuideUrl: "https://www.bmj.com/about-bmj/editorial-staff",
    impactFactor: 105.7,
    scope: "Research, education, news, comment for clinicians, researchers, educators worldwide.",
    manuscriptTypes: [
      { ...ORIG_3000, mainTextWordLimit: 2500, abstractWordLimit: 350, referencesMax: 30 },
      { ...BRIEF_REPORT, mainTextWordLimit: 1500 },
      SYSTEMATIC_REVIEW,
      PROTOCOL,
    ],
    defaultManuscriptType: "original_investigation",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-parens",
      authorListing: "all-up-to-3-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
      notes: "Vancouver numbered, et al after first three authors.",
    },
    figures: {
      format: "editable",
      minDpi: 300,
      allowedTypes: ["TIFF", "EPS", "PDF", "PNG"],
      captionLocation: "end-of-manuscript",
    },
    tables: { format: "editable-word", location: "end-of-manuscript" },
    required: {
      ...ICMJE_FULL,
      ppiStatement: true, // BMJ mandates PPI section
    },
    reviewerLens: [
      "Is the question clinically important and is the answer credible?",
      "Are the methods reproducible and is the analysis sound?",
      "Does the discussion proportionate to the results, with explicit limitations and equity considerations?",
      "Is the patient and public involvement (PPI) statement meaningful, not boilerplate?",
      "Is the data sharing statement specific and actionable?",
    ],
    editorLens: [
      "BMJ desk-rejects when generalisability to a global clinical readership is weak.",
      "PPI section must be present and substantive.",
      "Open data and transparency expectations are high.",
    ],
    tier: "A",
  },
  {
    id: "jama",
    name: "JAMA",
    publisher: "American Medical Association",
    homepage: "https://jamanetwork.com/journals/jama",
    authorGuideUrl: "https://jamanetwork.com/journals/jama/pages/instructions-for-authors",
    impactFactor: 120.7,
    scope: "Original research, reviews, and commentary for physicians worldwide.",
    manuscriptTypes: [
      { ...ORIG_3000, keyPointsRequired: true, referencesMax: 75, displayItemsMax: 5 },
      { ...BRIEF_REPORT, mainTextWordLimit: 600 }, // Research Letter
      SYSTEMATIC_REVIEW,
      PROTOCOL,
    ],
    defaultManuscriptType: "original_investigation",
    abstractStructure: "question-findings-meaning",
    abstractCustomSections: [
      "Importance",
      "Objective",
      "Design, Setting, and Participants",
      "Interventions/Exposures",
      "Main Outcomes and Measures",
      "Results",
      "Conclusions and Relevance",
    ],
    referenceStyle: {
      format: "ama-numbered",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: false,
      urlsAllowed: true,
      notes: "AMA style; numbered in order of appearance.",
    },
    figures: {
      format: "editable",
      minDpi: 300,
      allowedTypes: ["TIFF", "EPS", "PDF"],
      captionLocation: "below-figure",
    },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: [
      "Is the primary question novel, clinically relevant, and rigorously answered?",
      "Are statistical methods appropriate including pre-specification and multiplicity?",
      "Are Key Points (Question / Findings / Meaning) accurate and aligned with the results?",
      "Is the abstract structured per JAMA format (Importance through Conclusions and Relevance)?",
    ],
    editorLens: [
      "Original Investigations are limited to 3000 words and 5 display items.",
      "Authors must complete the JAMA-specific cover-letter checklist.",
      "Key Points are required and weighted heavily in screening.",
    ],
    tier: "A",
  },
  {
    id: "nejm",
    name: "New England Journal of Medicine",
    publisher: "Massachusetts Medical Society",
    homepage: "https://www.nejm.org/",
    authorGuideUrl: "https://www.nejm.org/author-center/manuscript-submission",
    impactFactor: 158.5,
    scope: "Original research and reviews of biomedical and clinical importance.",
    manuscriptTypes: [
      { ...ORIG_3000, mainTextWordLimit: 2700, abstractWordLimit: 250, referencesMax: 40, displayItemsMax: 5 },
      { ...BRIEF_REPORT, mainTextWordLimit: 600 }, // Research Letter
      CASE_REPORT,
    ],
    defaultManuscriptType: "original_investigation",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-parens",
      authorListing: "all-up-to-3-etal",
      journalAbbrev: "index-medicus",
      doiRequired: false,
      urlsAllowed: true,
    },
    figures: {
      format: "editable",
      minDpi: 600,
      allowedTypes: ["TIFF", "EPS"],
      captionLocation: "end-of-manuscript",
    },
    tables: { format: "editable-word", location: "end-of-manuscript" },
    required: ICMJE_FULL,
    reviewerLens: [
      "Is this finding likely to change clinical practice?",
      "Are the trial methods and CONSORT 2025 reporting complete?",
      "Are pre-specified primary outcome and analysis maintained without selective reporting?",
    ],
    editorLens: [
      "NEJM desk-rejects ~95% of submissions; novelty + magnitude + clinical impact must be exceptional.",
      "Trial registration and protocol availability are mandatory.",
    ],
    tier: "A",
  },
  {
    id: "lancet",
    name: "The Lancet",
    publisher: "Elsevier",
    homepage: "https://www.thelancet.com/",
    authorGuideUrl: "https://thelancet.com/pb/assets/raw/Lancet/authors/tlrm-info-for-authors.pdf",
    impactFactor: 168.9,
    scope: "Original research, reviews, commentary across all medical disciplines.",
    manuscriptTypes: [
      { ...ORIG_4500, mainTextWordLimit: 4500, abstractWordLimit: 300, referencesMax: 30, displayItemsMax: 5 },
      { ...BRIEF_REPORT, mainTextWordLimit: 2500 },
      SYSTEMATIC_REVIEW,
      PROTOCOL,
    ],
    defaultManuscriptType: "original_investigation",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-superscript",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
      notes: "Vancouver superscript; up to 6 authors listed in full.",
    },
    figures: {
      format: "redrawn-inhouse",
      minDpi: 300,
      allowedTypes: ["TIFF", "EPS", "PDF"],
      captionLocation: "end-of-manuscript",
      notes: "All figures redrawn in Lancet style by in-house illustrators.",
    },
    tables: { format: "editable-word", location: "end-of-manuscript" },
    required: ICMJE_FULL,
    reviewerLens: [
      "Is the trial design rigorous and globally relevant?",
      "Are funding sources and role of sponsor transparently described?",
      "Is the 'Research in context' panel (Evidence before / Added value / Implications) complete and accurate?",
    ],
    editorLens: [
      "Lancet requires a 'Research in context' panel; missing it triggers immediate revision.",
      "Display items capped at 5 (figures + tables combined).",
    ],
    tier: "A",
  },
  {
    id: "nature",
    name: "Nature",
    publisher: "Springer Nature",
    homepage: "https://www.nature.com/nature/",
    authorGuideUrl: "https://www.nature.com/nature/for-authors/formatting-guide",
    impactFactor: 64.8,
    scope: "Original research of outstanding scientific importance.",
    manuscriptTypes: [
      { ...ORIG_3000, mainTextWordLimit: 5000, abstractWordLimit: 200, referencesMax: 50, displayItemsMax: 6 },
      { ...BRIEF_REPORT, mainTextWordLimit: 2500 },
    ],
    defaultManuscriptType: "research_article",
    abstractStructure: "unstructured",
    referenceStyle: {
      format: "nature-superscript",
      authorListing: "all-up-to-5-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: false,
      notes: "Nature numerical superscripts; up to 5 authors listed.",
    },
    figures: {
      format: "high-res-image",
      minDpi: 300,
      allowedTypes: ["TIFF", "EPS", "PDF", "AI"],
      captionLocation: "end-of-manuscript",
    },
    tables: { format: "editable-word", location: "end-of-manuscript" },
    required: { ...ICMJE_FULL, ppiStatement: false, registrationStatement: false },
    reviewerLens: [
      "Is the work novel, broadly significant, and methodologically robust?",
      "Are claims supported by data with appropriate replication and controls?",
    ],
    editorLens: [
      "Nature desk-rejects most submissions; pre-submission inquiries encouraged.",
      "All data, code, and materials must be available; statements explicit.",
    ],
    tier: "A",
  },
  {
    id: "nature-medicine",
    name: "Nature Medicine",
    publisher: "Springer Nature",
    homepage: "https://www.nature.com/nm/",
    authorGuideUrl: "https://www.nature.com/nm/submission-guidelines/aip-and-formatting",
    impactFactor: 87.2,
    scope: "Biomedical research with high clinical impact.",
    manuscriptTypes: [
      { ...ORIG_4500, abstractWordLimit: 200, displayItemsMax: 7 },
      SYSTEMATIC_REVIEW,
    ],
    defaultManuscriptType: "research_article",
    abstractStructure: "unstructured",
    referenceStyle: {
      format: "nature-superscript",
      authorListing: "all-up-to-5-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: false,
    },
    figures: {
      format: "high-res-image",
      minDpi: 300,
      allowedTypes: ["TIFF", "EPS", "PDF"],
      captionLocation: "end-of-manuscript",
    },
    tables: { format: "editable-word", location: "end-of-manuscript" },
    required: ICMJE_FULL,
    reviewerLens: [
      "Does the work advance translational or clinical understanding meaningfully?",
      "Are translational claims supported by appropriate preclinical and/or clinical evidence?",
    ],
    editorLens: ["Pre-submission inquiry recommended for very high-impact claims."],
    tier: "A",
  },
  {
    id: "plos-medicine",
    name: "PLOS Medicine",
    publisher: "Public Library of Science",
    homepage: "https://journals.plos.org/plosmedicine/",
    authorGuideUrl: "https://journals.plos.org/plosmedicine/s/submission-guidelines",
    impactFactor: 15.8,
    scope: "Open-access journal for research with major public-health impact.",
    manuscriptTypes: [
      { ...ORIG_4500, mainTextWordLimit: 5000, displayItemsMax: 8 },
      SYSTEMATIC_REVIEW,
      PROTOCOL,
    ],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-brackets",
      authorListing: "all-up-to-5-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: {
      format: "editable",
      minDpi: 300,
      allowedTypes: ["TIFF", "EPS", "PDF"],
      captionLocation: "end-of-manuscript",
    },
    tables: { format: "editable-word", location: "in-text" },
    required: { ...ICMJE_FULL, ppiStatement: false },
    reviewerLens: ["Public-health relevance; transparency of methods; open data."],
    editorLens: ["Open data required unless legally restricted."],
    tier: "A",
  },
  {
    id: "ann-intern-med",
    name: "Annals of Internal Medicine",
    publisher: "American College of Physicians",
    homepage: "https://www.acpjournals.org/journal/aim",
    authorGuideUrl: "https://www.acpjournals.org/journal/aim/authors",
    impactFactor: 39.2,
    scope: "Internal medicine research and reviews.",
    manuscriptTypes: [{ ...ORIG_3000, mainTextWordLimit: 3500, displayItemsMax: 5 }, SYSTEMATIC_REVIEW],
    defaultManuscriptType: "original_investigation",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-parens",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: false,
      urlsAllowed: true,
    },
    figures: {
      format: "editable",
      minDpi: 300,
      allowedTypes: ["TIFF", "EPS", "PDF"],
      captionLocation: "below-figure",
    },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: ["Internal-medicine relevance; rigorous methods; clinical implications."],
    editorLens: ["Annals emphasizes methodological rigor and statistical pre-specification."],
    tier: "A",
  },
  {
    id: "jama-network-open",
    name: "JAMA Network Open",
    publisher: "American Medical Association",
    homepage: "https://jamanetwork.com/journals/jamanetworkopen",
    authorGuideUrl: "https://jamanetwork.com/journals/jamanetworkopen/pages/instructions-for-authors",
    impactFactor: 13.8,
    scope: "Open-access general medical research.",
    manuscriptTypes: [
      { ...ORIG_3000, mainTextWordLimit: 3000, keyPointsRequired: true, referencesMax: 75 },
    ],
    defaultManuscriptType: "original_investigation",
    abstractStructure: "question-findings-meaning",
    abstractCustomSections: [
      "Importance",
      "Objective",
      "Design, Setting, and Participants",
      "Exposures/Interventions",
      "Main Outcomes and Measures",
      "Results",
      "Conclusions and Relevance",
    ],
    referenceStyle: {
      format: "ama-numbered",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: false,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: ["Same rigor as JAMA but open-access and broader scope."],
    editorLens: ["Key Points required; structured abstract per JAMA format."],
    tier: "A",
  },
  {
    id: "bmj-open",
    name: "BMJ Open",
    publisher: "BMJ Publishing Group",
    homepage: "https://bmjopen.bmj.com/",
    authorGuideUrl: "https://bmjopen.bmj.com/pages/authors/",
    impactFactor: 2.9,
    scope: "Open-access general medical research, no impact-bar selection.",
    manuscriptTypes: [
      { ...ORIG_4500, mainTextWordLimit: 4000, referencesMax: 60 },
      PROTOCOL,
      SYSTEMATIC_REVIEW,
    ],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-parens",
      authorListing: "all-up-to-3-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "end-of-manuscript" },
    tables: { format: "editable-word", location: "end-of-manuscript" },
    required: { ...ICMJE_FULL, ppiStatement: true },
    reviewerLens: ["Methodological soundness over novelty."],
    editorLens: ["No impact-bar; selection focuses on methodology and ethics."],
    tier: "A",
  },
  {
    id: "cureus",
    name: "Cureus Journal of Medical Science",
    publisher: "Cureus (Springer Nature)",
    homepage: "https://www.cureus.com/",
    authorGuideUrl: "https://www.cureus.com/author_guide",
    impactFactor: 1.0,
    scope: "Open-access general medical journal, peer-reviewed.",
    manuscriptTypes: [
      { ...ORIG_3000 },
      CASE_REPORT,
      SYSTEMATIC_REVIEW,
    ],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-brackets",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "PNG", "JPG"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: { ...ICMJE_FULL, registrationStatement: true },
    reviewerLens: ["Standard biomedical reporting expectations."],
    editorLens: ["Rapid peer review; preprint-friendly."],
    tier: "A",
  },
  {
    id: "frontiers-medicine",
    name: "Frontiers in Medicine",
    publisher: "Frontiers Media",
    homepage: "https://www.frontiersin.org/journals/medicine",
    authorGuideUrl: "https://www.frontiersin.org/journals/medicine/for-authors/author-guidelines",
    impactFactor: 3.1,
    scope: "Open-access medical research across specialties.",
    manuscriptTypes: [
      { ...ORIG_4500, mainTextWordLimit: 12000, displayItemsMax: 15 },
      SYSTEMATIC_REVIEW,
      CASE_REPORT,
    ],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-brackets",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "full-name",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "PNG", "JPG", "EPS"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: { ...ICMJE_FULL, ppiStatement: false },
    reviewerLens: ["Methodologically sound; relevant to the medical specialty section."],
    editorLens: ["Frontiers has section-specific guidelines; consult the target section."],
    tier: "A",
  },
  {
    id: "bmc-medicine",
    name: "BMC Medicine",
    publisher: "Springer Nature (BMC)",
    homepage: "https://bmcmedicine.biomedcentral.com/",
    authorGuideUrl: "https://bmcmedicine.biomedcentral.com/submission-guidelines",
    impactFactor: 9.3,
    scope: "Open-access broad-scope general medical research.",
    manuscriptTypes: [{ ...ORIG_4500, mainTextWordLimit: 5000, referencesMax: 60 }, SYSTEMATIC_REVIEW, PROTOCOL],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-brackets",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF", "PNG"], captionLocation: "end-of-manuscript" },
    tables: { format: "editable-word", location: "in-text" },
    required: { ...ICMJE_FULL, ppiStatement: true },
    reviewerLens: ["High methodological standard; broad medical relevance."],
    editorLens: ["Open access; data availability statement required."],
    tier: "A",
  },
  {
    id: "elife",
    name: "eLife",
    publisher: "eLife Sciences Publications",
    homepage: "https://elifesciences.org/",
    authorGuideUrl: "https://elifesciences.org/inside-elife/c5cb8b65/full-guide-the-elife-publishing-process",
    impactFactor: 6.4,
    scope: "Open-access life and biomedical science.",
    manuscriptTypes: [{ ...ORIG_4500, mainTextWordLimit: 8000, displayItemsMax: 10 }],
    defaultManuscriptType: "research_article",
    abstractStructure: "unstructured",
    referenceStyle: {
      format: "vancouver-numbered-brackets",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "PDF", "AI"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: ["Open-review model; reviewers see one another's reports."],
    editorLens: ["Innovative open-review process; preprints encouraged."],
    tier: "A",
  },
  {
    id: "cochrane-reviews",
    name: "Cochrane Database of Systematic Reviews",
    publisher: "Cochrane / Wiley",
    homepage: "https://www.cochranelibrary.com/",
    authorGuideUrl: "https://documentation.cochrane.org/display/PROD/Cochrane+Author+Documentation",
    impactFactor: 8.4,
    scope: "Systematic reviews of healthcare interventions.",
    manuscriptTypes: [SYSTEMATIC_REVIEW, PROTOCOL],
    defaultManuscriptType: "systematic_review",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-parens",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: { ...ICMJE_FULL, ppiStatement: false },
    reviewerLens: ["Strict Cochrane Handbook adherence; GRADE certainty; transparent search."],
    editorLens: ["Cochrane reviews follow MECIR conduct standards; PROSPERO registration mandatory."],
    tier: "A",
  },
  {
    id: "jama-surgery",
    name: "JAMA Surgery",
    publisher: "American Medical Association",
    homepage: "https://jamanetwork.com/journals/jamasurgery",
    authorGuideUrl: "https://jamanetwork.com/journals/jamasurgery/pages/instructions-for-authors",
    impactFactor: 16.9,
    scope: "Surgical research and reviews.",
    manuscriptTypes: [
      { ...ORIG_3000, keyPointsRequired: true },
      CASE_REPORT,
      SYSTEMATIC_REVIEW,
    ],
    defaultManuscriptType: "original_investigation",
    abstractStructure: "question-findings-meaning",
    abstractCustomSections: [
      "Importance",
      "Objective",
      "Design, Setting, and Participants",
      "Interventions",
      "Main Outcomes and Measures",
      "Results",
      "Conclusions and Relevance",
    ],
    referenceStyle: {
      format: "ama-numbered",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: false,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: ["Surgical methods detail; complication grading; long-term outcomes."],
    editorLens: ["Use Clavien-Dindo for complications; report surgeon experience."],
    tier: "A",
  },
  {
    id: "lancet-oncology",
    name: "The Lancet Oncology",
    publisher: "Elsevier",
    homepage: "https://www.thelancet.com/journals/lanonc/home",
    authorGuideUrl: "https://www.thelancet.com/pb/assets/raw/Lancet/authors/lancet-oncology-information-for-authors.pdf",
    impactFactor: 51.0,
    scope: "Oncology — high-impact clinical, translational, and epidemiologic research.",
    manuscriptTypes: [{ ...ORIG_4500, mainTextWordLimit: 4500, displayItemsMax: 5 }, SYSTEMATIC_REVIEW],
    defaultManuscriptType: "original_investigation",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-superscript",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "redrawn-inhouse", minDpi: 300, allowedTypes: ["TIFF", "EPS"], captionLocation: "end-of-manuscript" },
    tables: { format: "editable-word", location: "end-of-manuscript" },
    required: ICMJE_FULL,
    reviewerLens: ["Oncology-specific endpoints (PFS, OS, ORR) defined per RECIST."],
    editorLens: ["Lancet 'Research in context' panel required."],
    tier: "A",
  },
  {
    id: "npj-digital-medicine",
    name: "npj Digital Medicine",
    publisher: "Springer Nature",
    homepage: "https://www.nature.com/npjdigitalmed/",
    authorGuideUrl: "https://www.nature.com/npjdigitalmed/submission-guidelines",
    impactFactor: 15.3,
    scope: "Open-access digital health, AI, and digital therapeutics research.",
    manuscriptTypes: [{ ...ORIG_4500, mainTextWordLimit: 5000, displayItemsMax: 8 }],
    defaultManuscriptType: "research_article",
    abstractStructure: "unstructured",
    referenceStyle: {
      format: "nature-superscript",
      authorListing: "all-up-to-5-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: false,
    },
    figures: { format: "high-res-image", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "end-of-manuscript" },
    tables: { format: "editable-word", location: "end-of-manuscript" },
    required: ICMJE_FULL,
    reviewerLens: ["Algorithm transparency; external validation; equity considerations."],
    editorLens: ["AI/ML reporting must follow CONSORT-AI / SPIRIT-AI / TRIPOD+AI / CLAIM as applicable."],
    tier: "A",
  },
  {
    id: "circulation",
    name: "Circulation",
    publisher: "American Heart Association / Wolters Kluwer",
    homepage: "https://www.ahajournals.org/journal/circ",
    authorGuideUrl: "https://www.ahajournals.org/manuscript-submission",
    impactFactor: 37.8,
    scope: "Cardiovascular research and reviews.",
    manuscriptTypes: [{ ...ORIG_3000, mainTextWordLimit: 6000, referencesMax: 60 }],
    defaultManuscriptType: "original_investigation",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "ama-numbered",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS"], captionLocation: "end-of-manuscript" },
    tables: { format: "editable-word", location: "end-of-manuscript" },
    required: ICMJE_FULL,
    reviewerLens: ["Cardiology-specific endpoints (MACE, hospitalisation, mortality)."],
    editorLens: ["AHA Scientific Statement template available; Circulation emphasizes clinical impact."],
    tier: "A",
  },
  {
    id: "mdpi-jcm",
    name: "Journal of Clinical Medicine (MDPI)",
    publisher: "MDPI",
    homepage: "https://www.mdpi.com/journal/jcm",
    authorGuideUrl: "https://www.mdpi.com/journal/jcm/instructions",
    impactFactor: 3.0,
    scope: "Open-access clinical medicine.",
    manuscriptTypes: [{ ...ORIG_3000 }, SYSTEMATIC_REVIEW, CASE_REPORT],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "elsevier-numbered",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "full-name",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "PNG", "PDF"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: { ...ICMJE_FULL, ppiStatement: false },
    reviewerLens: ["Standard biomedical reporting expectations."],
    editorLens: ["Rapid open-access publication."],
    tier: "A",
  },
];

/* ============================================================
   Tier B — publisher templates (generic style for journals
   whose specific page hasn't been hand-curated).
   ============================================================ */

export const publisherTemplates: JournalSpec[] = [
  {
    id: "template.elsevier",
    name: "Elsevier journal (generic template)",
    publisher: "Elsevier",
    homepage: "https://www.elsevier.com/journals",
    authorGuideUrl: "https://www.elsevier.com/researcher/author",
    manuscriptTypes: [{ ...ORIG_4500 }, SYSTEMATIC_REVIEW, CASE_REPORT],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "elsevier-numbered",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: ["Match-journal scope; methodologic rigour."],
    editorLens: ["Most Elsevier journals follow Vancouver numbered style."],
    tier: "B",
  },
  {
    id: "template.springer-nature",
    name: "Springer Nature journal (generic template)",
    publisher: "Springer Nature",
    homepage: "https://www.springernature.com/",
    authorGuideUrl: "https://www.springernature.com/gp/authors",
    manuscriptTypes: [{ ...ORIG_4500 }, SYSTEMATIC_REVIEW, CASE_REPORT, PROTOCOL],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-brackets",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF", "PNG"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: ["Match-journal scope; methodologic rigour."],
    editorLens: ["Springer Nature has journal-specific style sheets; confirm before submission."],
    tier: "B",
  },
  {
    id: "template.wiley",
    name: "Wiley journal (generic template)",
    publisher: "Wiley",
    homepage: "https://onlinelibrary.wiley.com/",
    authorGuideUrl: "https://authorservices.wiley.com/author-resources/Journal-Authors/index.html",
    manuscriptTypes: [{ ...ORIG_4500 }, SYSTEMATIC_REVIEW, CASE_REPORT],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "ama-numbered",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: ["Match-journal scope; methodologic rigour."],
    editorLens: ["Wiley journals vary; verify per-journal author guidelines."],
    tier: "B",
  },
  {
    id: "template.oxford",
    name: "Oxford Academic journal (generic template)",
    publisher: "Oxford University Press",
    homepage: "https://academic.oup.com/journals",
    authorGuideUrl: "https://academic.oup.com/journals/pages/authors",
    manuscriptTypes: [{ ...ORIG_4500 }, SYSTEMATIC_REVIEW],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-parens",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: ["Match-journal scope; methodologic rigour."],
    editorLens: ["OUP journals vary in style; confirm before submission."],
    tier: "B",
  },
  {
    id: "template.sage",
    name: "SAGE journal (generic template)",
    publisher: "SAGE Publishing",
    homepage: "https://journals.sagepub.com/",
    authorGuideUrl: "https://us.sagepub.com/en-us/nam/manuscript-submission-guidelines",
    manuscriptTypes: [{ ...ORIG_4500 }, SYSTEMATIC_REVIEW],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-parens",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: ["Match-journal scope; methodologic rigour."],
    editorLens: ["SAGE journals usually follow Vancouver or APA — confirm per journal."],
    tier: "B",
  },
  {
    id: "template.taylor-francis",
    name: "Taylor & Francis journal (generic template)",
    publisher: "Taylor & Francis",
    homepage: "https://taylorandfrancis.com/journals/",
    authorGuideUrl: "https://taylorandfrancis.com/journals/authors/",
    manuscriptTypes: [{ ...ORIG_4500 }, SYSTEMATIC_REVIEW],
    defaultManuscriptType: "research_article",
    abstractStructure: "background-methods-results-conclusions",
    referenceStyle: {
      format: "vancouver-numbered-parens",
      authorListing: "all-up-to-6-etal",
      journalAbbrev: "index-medicus",
      doiRequired: true,
      urlsAllowed: true,
    },
    figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "below-figure" },
    tables: { format: "editable-word", location: "in-text" },
    required: ICMJE_FULL,
    reviewerLens: ["Match-journal scope; methodologic rigour."],
    editorLens: ["T&F journals vary; confirm style per journal."],
    tier: "B",
  },
];

/* ============================================================
   Tier C — "Other" — fetched live (or ICMJE generic fallback).
   ============================================================ */

export const icmjeGenericFallback: JournalSpec = {
  id: "icmje-generic",
  name: "ICMJE generic (unspecified journal)",
  publisher: "—",
  homepage: "https://www.icmje.org/",
  authorGuideUrl: "https://www.icmje.org/recommendations/",
  manuscriptTypes: [{ ...ORIG_3000 }, BRIEF_REPORT, SYSTEMATIC_REVIEW, CASE_REPORT, PROTOCOL],
  defaultManuscriptType: "original_investigation",
  abstractStructure: "background-methods-results-conclusions",
  referenceStyle: {
    format: "vancouver-numbered-parens",
    authorListing: "all-up-to-6-etal",
    journalAbbrev: "index-medicus",
    doiRequired: true,
    urlsAllowed: true,
  },
  figures: { format: "editable", minDpi: 300, allowedTypes: ["TIFF", "EPS", "PDF"], captionLocation: "below-figure" },
  tables: { format: "editable-word", location: "in-text" },
  required: ICMJE_FULL,
  reviewerLens: [
    "Follow the relevant EQUATOR reporting guideline for the design.",
    "Statistical methods pre-specified and appropriate.",
    "Limitations explicitly discussed.",
  ],
  editorLens: [
    "ICMJE-conformant journal expectations apply.",
    "Trial registration, ICMJE author criteria, data sharing statement required.",
  ],
  tier: "C",
};

export const allJournalSpecs = [...journals, ...publisherTemplates];

export const journalById = (id: string): JournalSpec | undefined => {
  if (!id) return undefined;
  if (id.startsWith("other:")) return undefined; // resolved server-side
  return allJournalSpecs.find((j) => j.id === id) || (id === "icmje-generic" ? icmjeGenericFallback : undefined);
};
