/**
 * Curated international medical journal seed.
 *
 * This is a *representative* high-value seed (flagship SCIE journals, strong
 * ESCI/emerging titles, and broad specialty journals) — NOT the full universe.
 * The full universe (~2.1k SCIE medical, ~12k ESCI/emerging, ~35k PubMed) is
 * produced at deploy time by scripts/ingest-journals.mjs, which pulls from
 * DOAJ + Crossref + OpenAlex + NLM and writes lib/journals/generated.ts.
 * The finder merges curated + generated, de-duping by ISSN/name. Curated
 * entries win on conflict because their indexing/metrics are hand-verified.
 */

import type { JournalRecord } from "./types";

const v = {
  wos: "https://mjl.clarivate.com/home",
  scopus: "https://www.scopus.com/sources",
  nlm: "https://www.ncbi.nlm.nih.gov/nlmcatalog/journals/",
  doaj: "https://doaj.org/",
  scimago: "https://www.scimagojr.com/journalsearch.php",
};

export const internationalJournals: JournalRecord[] = [
  // ---- General & internal medicine flagships (SCIE Q1) ----
  {
    id: "nejm", name: "New England Journal of Medicine", abbrev: "N Engl J Med",
    publisher: "Massachusetts Medical Society", country: "United States",
    issnPrint: "0028-4793", issnOnline: "1533-4406", homepage: "https://www.nejm.org/",
    authorGuideUrl: "https://www.nejm.org/author-center", scope: "Highest-impact general and internal medicine; practice-changing clinical trials and major findings.",
    specialties: ["general medicine", "internal medicine", "clinical trials"],
    acceptedTypes: ["original_investigation", "review", "correspondence"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 78.5, quartile: "Q1", metricsYear: 2024 }, oaModel: "subscription",
    apcModel: "subscription", freeApc: true,
    authorGuidelinesSummary: "Original Articles ~2700 words, structured abstract <=350 words; rigorous trial pre-registration and full data-sharing statement required; ICMJE disclosure mandatory.",
    reviewerProcess: "Single-blind external peer review; highly selective (~4% acceptance), ~1-2 weeks to initial editorial triage.",
    decisionTimeDays: 14, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "Subscription journal: no APC to publish, but access is paywalled. IF corrected to JCR 2024 (78.5) from post-COVID normalization.",
  },
  {
    id: "lancet", name: "The Lancet", abbrev: "Lancet",
    publisher: "Elsevier", country: "United Kingdom",
    issnPrint: "0140-6736", issnOnline: "1474-547X", homepage: "https://www.thelancet.com/",
    authorGuideUrl: "https://www.thelancet.com/for-authors", scope: "Global general medicine; major clinical and public-health research.",
    specialties: ["general medicine", "internal medicine", "public health", "global health"],
    acceptedTypes: ["original_investigation", "review", "correspondence"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 88.5, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Articles ~3000-5000 words with structured summary; mandatory trial registration, full data-sharing and role-of-funder statements; CONSORT/STROBE/PRISMA flow diagrams required as relevant.",
    reviewerProcess: "Single-blind external review with statistical review; ~1 week to initial editorial decision, weeks for full review.",
    decisionTimeDays: 21, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "Now ranked #1 in General & Internal Medicine by JCR 2024 (IF 88.5), surpassing NEJM.",
  },
  {
    id: "jama", name: "JAMA", abbrev: "JAMA",
    publisher: "American Medical Association", country: "United States",
    issnPrint: "0098-7484", issnOnline: "1538-3598", homepage: "https://jamanetwork.com/journals/jama",
    authorGuideUrl: "https://jamanetwork.com/journals/jama/pages/instructions-for-authors", scope: "General medicine; clinical research, reviews, and viewpoints.",
    specialties: ["general medicine", "internal medicine", "clinical trials"],
    acceptedTypes: ["original_investigation", "review", "viewpoint"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 55.0, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original Investigation <=3000 words, structured abstract <=350 words; trial registration, data-sharing statement, and reporting-guideline checklist required at submission.",
    reviewerProcess: "Single-blind external peer review plus statistical review; first decision typically within a few weeks.",
    decisionTimeDays: 28, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA", "TRIPOD"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF corrected to JCR 2024 (55.0).",
  },
  {
    id: "bmj", name: "The BMJ", abbrev: "BMJ",
    publisher: "BMJ Publishing Group", country: "United Kingdom",
    issnPrint: "0959-8138", issnOnline: "1756-1833", homepage: "https://www.bmj.com/",
    authorGuideUrl: "https://www.bmj.com/about-bmj/resources-authors", scope: "General medicine, evidence-based practice, and health policy.",
    specialties: ["general medicine", "public health", "health policy", "epidemiology"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 42.7, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Research articles use IMRaD with a structured abstract; mandatory data-sharing, patient/public involvement statement, and reporting-guideline checklist (CONSORT/STROBE/PRISMA/STARD).",
    reviewerProcess: "Transparent (open) peer review — signed reports published with the article; first decision in ~3-4 weeks.",
    decisionTimeDays: 28, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA", "STARD"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF corrected to JCR 2024 (42.7) after post-COVID normalization. Uses fully open peer review.",
  },
  {
    id: "annals-im", name: "Annals of Internal Medicine", abbrev: "Ann Intern Med",
    publisher: "American College of Physicians", country: "United States",
    issnPrint: "0003-4819", issnOnline: "1539-3704", homepage: "https://www.acpjournals.org/journal/aim",
    authorGuideUrl: "https://www.acpjournals.org/journal/aim/authors", scope: "Internal medicine clinical research and guidelines.",
    specialties: ["internal medicine", "general medicine", "clinical research"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 19.6, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original research structured abstract <=275 words; reproducible-research statement, trial registration, and reporting-guideline checklist required.",
    reviewerProcess: "Single-blind external peer review with statistical review; first decision usually within ~3-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA", "TRIPOD"], dataConfidence: "curated", verifyUrls: v,
  },
  {
    id: "plos-med", name: "PLOS Medicine", abbrev: "PLoS Med",
    publisher: "Public Library of Science", country: "United States",
    issnOnline: "1549-1676", homepage: "https://journals.plos.org/plosmedicine/",
    authorGuideUrl: "https://journals.plos.org/plosmedicine/s/submission-guidelines", scope: "Global medicine and public health; fully open access.",
    specialties: ["general medicine", "public health", "global health", "epidemiology"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 15.8, quartile: "Q1", metricsYear: 2024 }, oaModel: "gold", apcUsd: 5300,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Research articles have no strict length limit but require structured abstract, data-availability statement, and reporting-guideline checklist; strong emphasis on global-health relevance.",
    reviewerProcess: "Single-blind external review with academic editor; ~4-6 weeks to first decision.",
    decisionTimeDays: 42, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / PLOS fees page",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "PLOS moving flagship titles toward Community Action Publishing; institutional agreements may waive fees.",
  },
  {
    id: "bmc-medicine", name: "BMC Medicine", abbrev: "BMC Med",
    publisher: "BMC (Springer Nature)", country: "United Kingdom",
    issnOnline: "1741-7015", homepage: "https://bmcmedicine.biomedcentral.com/",
    authorGuideUrl: "https://bmcmedicine.biomedcentral.com/submission-guidelines", scope: "Broad medicine; open access flagship of the BMC series.",
    specialties: ["general medicine", "internal medicine", "epidemiology", "public health"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 8.3, quartile: "Q1", metricsYear: 2024 }, oaModel: "gold", apcUsd: 4190,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "No word limit on main text; structured abstract, data-availability and ethics statements, and relevant reporting-guideline checklist required at submission.",
    reviewerProcess: "Single-blind external review; ~6-8 weeks to first decision. Springer Nature country-tiered APC pricing applies.",
    decisionTimeDays: 49, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / BMC fees page",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "APC updated to ~$4190 (2025/26); part of Springer Nature country-tiered pricing pilot. IF JCR 2024 (8.3).",
  },
  {
    id: "plos-one", name: "PLOS ONE", abbrev: "PLoS One",
    publisher: "Public Library of Science", country: "United States",
    issnOnline: "1932-6203", homepage: "https://journals.plos.org/plosone/",
    authorGuideUrl: "https://journals.plos.org/plosone/s/submission-guidelines", scope: "Multidisciplinary; rigorous-but-not-novelty-gated, very broad scope including all medical fields.",
    specialties: ["multidisciplinary", "general medicine", "public health", "biomedical"],
    acceptedTypes: ["original_investigation", "systematic_review", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 3.7, quartile: "Q2", metricsYear: 2024 }, oaModel: "gold", apcUsd: 1695,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Judged on scientific/technical soundness, not novelty or impact; requires data-availability statement, ethics/competing-interests declarations, and reporting-guideline checklists.",
    reviewerProcess: "Single-blind review by academic editor + reviewers; median ~5-6 weeks to first decision; high acceptance for sound work.",
    decisionTimeDays: 40, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / PLOS fees page ($1,695)",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA", "ARRIVE"], dataConfidence: "curated", verifyUrls: v,
    notes: "Large-scope megajournal; good fit for sound studies that are a niche fit elsewhere. APC ~$1,695 (2026).",
  },
  {
    id: "cureus", name: "Cureus Journal of Medical Science", abbrev: "Cureus",
    publisher: "Springer Nature", country: "United States",
    issnOnline: "2168-8184", homepage: "https://www.cureus.com/",
    authorGuideUrl: "https://www.cureus.com/author_guide", scope: "Broad medicine and case reports; rapid open-access publishing.",
    specialties: ["general medicine", "case reports", "multidisciplinary"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "none", scopus: "unknown", pubmed: "indexed", medline: "not-indexed", pmc: "indexed", doaj: "unknown" },
    metrics: { metricsYear: 2024 }, oaModel: "gold", apcUsd: 0,
    apcModel: "none", freeApc: true,
    authorGuidelinesSummary: "Free to publish; uses a structured template (SIQ scoring); case reports require CARE-style structure, ethics approval and patient consent; rapid turnaround.",
    reviewerProcess: "Editor-led plus optional community peer review (SIQ); fast, often days to a few weeks.",
    decisionTimeDays: 21, verifiedAt: "2026-05-30", dataSource: "Cureus newsroom / Web of Science",
    endorsedGuidelines: ["ICMJE", "CARE", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "DELISTED from Web of Science effective Oct 27, 2025 (will not get a 2025 JIF); still PubMed/PMC indexed, not MEDLINE. Free APC. Popular for case reports.",
  },

  // ---- Cardiology ----
  {
    id: "circulation", name: "Circulation", abbrev: "Circulation",
    publisher: "American Heart Association (Wolters Kluwer)", country: "United States",
    issnPrint: "0009-7322", issnOnline: "1524-4539", homepage: "https://www.ahajournals.org/journal/circ",
    authorGuideUrl: "https://www.ahajournals.org/circ/author-instructions", scope: "Cardiovascular medicine and science.",
    specialties: ["cardiology", "cardiovascular", "internal medicine"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 38.6, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Strict word/figure limits by article type; mandatory trial registration, data-sharing statement, and AHA reporting-guideline compliance (CONSORT/STROBE).",
    reviewerProcess: "Single-blind external peer review; first decision typically ~3-5 weeks.",
    decisionTimeDays: 28, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (38.6).",
  },
  {
    id: "eur-heart-j", name: "European Heart Journal", abbrev: "Eur Heart J",
    publisher: "Oxford University Press (ESC)", country: "United Kingdom",
    issnPrint: "0195-668X", issnOnline: "1522-9645", homepage: "https://academic.oup.com/eurheartj",
    authorGuideUrl: "https://academic.oup.com/eurheartj/pages/General_Instructions", scope: "Cardiovascular medicine; flagship of the European Society of Cardiology.",
    specialties: ["cardiology", "cardiovascular"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 35.6, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Clinical research papers ~5000 words with structured abstract; trial registration, data-sharing, and ESC guideline alignment required; rigorous statistical review.",
    reviewerProcess: "Single-blind external review with statistical assessment; first decision ~3-4 weeks.",
    decisionTimeDays: 28, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / ESC impact factors 2024",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (35.6).",
  },

  // ---- Oncology ----
  {
    id: "jco", name: "Journal of Clinical Oncology", abbrev: "J Clin Oncol",
    publisher: "American Society of Clinical Oncology", country: "United States",
    issnPrint: "0732-183X", issnOnline: "1527-7755", homepage: "https://ascopubs.org/journal/jco",
    authorGuideUrl: "https://ascopubs.org/jco/authors", scope: "Clinical oncology and cancer research.",
    specialties: ["oncology", "hematology", "cancer"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 41.9, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original Reports ~3500 words with structured abstract; mandatory trial registration, data-sharing statement, and CONSORT/REMARK compliance. No APC for the flagship JCO (hybrid OA route is fee-free).",
    reviewerProcess: "Single-blind external peer review with statistical review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / ASCO author FAQ",
    endorsedGuidelines: ["ICMJE", "CONSORT", "REMARK"], dataConfidence: "curated", verifyUrls: v,
    notes: "Flagship JCO has no publication fee; separate JCO OA/GO titles charge APCs. IF JCR 2024 (41.9).",
  },
  {
    id: "frontiers-oncology", name: "Frontiers in Oncology", abbrev: "Front Oncol",
    publisher: "Frontiers Media", country: "Switzerland",
    issnOnline: "2234-943X", homepage: "https://www.frontiersin.org/journals/oncology",
    authorGuideUrl: "https://www.frontiersin.org/guidelines/author-guidelines", scope: "Broad oncology; open access.",
    specialties: ["oncology", "cancer", "radiation oncology"],
    acceptedTypes: ["original_investigation", "systematic_review", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 3.1, quartile: "Q2", metricsYear: 2024 }, oaModel: "gold", apcUsd: 2950,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Article-type-specific structure with structured abstract; data-availability and ethics statements required; uses Frontiers' collaborative review platform. Fee support/waivers available.",
    reviewerProcess: "Collaborative, identity-disclosed (open) review via interactive platform; ~6-9 weeks to first decision.",
    decisionTimeDays: 60, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / Frontiers fee policy",
    endorsedGuidelines: ["ICMJE", "CONSORT", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (~3.1). Frontiers waives substantial fees annually (waiver-available in practice).",
  },

  // ---- Public health / epidemiology ----
  {
    id: "ije", name: "International Journal of Epidemiology", abbrev: "Int J Epidemiol",
    publisher: "Oxford University Press", country: "United Kingdom",
    issnPrint: "0300-5771", issnOnline: "1464-3685", homepage: "https://academic.oup.com/ije",
    authorGuideUrl: "https://academic.oup.com/ije/pages/General_Instructions", scope: "Epidemiology and population health methods.",
    specialties: ["epidemiology", "public health", "biostatistics"],
    acceptedTypes: ["original_investigation", "systematic_review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 6.4, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original articles ~3500 words with structured abstract; STROBE-compliant reporting and a data-availability statement required; strong methodological/statistical emphasis.",
    reviewerProcess: "Single-blind external peer review; first decision ~4-8 weeks.",
    decisionTimeDays: 42, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
  },
  {
    id: "ijerph", name: "International Journal of Environmental Research and Public Health", abbrev: "Int J Environ Res Public Health",
    publisher: "MDPI", country: "Switzerland",
    issnOnline: "1660-4601", homepage: "https://www.mdpi.com/journal/ijerph",
    authorGuideUrl: "https://www.mdpi.com/journal/ijerph/instructions", scope: "Environmental health and public health; open access.",
    specialties: ["public health", "environmental health", "epidemiology", "occupational health"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "none", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { metricsYear: 2024 }, oaModel: "gold", apcUsd: 2500,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original articles ~4000 words; structured abstract, ethics and data-availability statements, and reporting-guideline checklist required.",
    reviewerProcess: "Single-blind external review; fast track (~median 30-40 days to first decision).",
    decisionTimeDays: 38, verifiedAt: "2026-05-30", dataSource: "Retraction Watch / Clarivate / MDPI announcements",
    endorsedGuidelines: ["ICMJE", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "Still DELISTED from Web of Science (discontinued Feb 2023; not reinstated as of May 2026). Remains Scopus/MEDLINE/DOAJ indexed — no current JIF.",
  },

  // ---- Surgery ----
  {
    id: "ann-surg", name: "Annals of Surgery", abbrev: "Ann Surg",
    publisher: "Wolters Kluwer", country: "United States",
    issnPrint: "0003-4932", issnOnline: "1528-1140", homepage: "https://journals.lww.com/annalsofsurgery/",
    authorGuideUrl: "https://journals.lww.com/annalsofsurgery/pages/informationforauthors.aspx", scope: "Surgical science and practice.",
    specialties: ["surgery", "general surgery"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 6.5, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original articles ~3500 words with structured abstract; mandatory reporting-guideline checklist (CONSORT/STROBE) and data-sharing statement.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (6.5).",
  },

  // ---- Pediatrics ----
  {
    id: "pediatrics", name: "Pediatrics", abbrev: "Pediatrics",
    publisher: "American Academy of Pediatrics", country: "United States",
    issnPrint: "0031-4005", issnOnline: "1098-4275", homepage: "https://publications.aap.org/pediatrics",
    authorGuideUrl: "https://publications.aap.org/pediatrics/pages/authorguidelines", scope: "General pediatrics and child health.",
    specialties: ["pediatrics", "child health"],
    acceptedTypes: ["original_investigation", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 4.0, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Article-type-specific limits with structured abstract; trial registration, data-sharing, and reporting-guideline checklist required; strong child-health focus.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "CARE"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (~4.0).",
  },

  // ---- Endocrinology / diabetes ----
  {
    id: "diabetes-care", name: "Diabetes Care", abbrev: "Diabetes Care",
    publisher: "American Diabetes Association", country: "United States",
    issnPrint: "0149-5992", issnOnline: "1935-5548", homepage: "https://diabetesjournals.org/care",
    authorGuideUrl: "https://diabetesjournals.org/care/pages/instructions-for-authors", scope: "Clinical diabetes research and care.",
    specialties: ["endocrinology", "diabetes", "internal medicine"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 16.6, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original articles ~4000 words with structured abstract; trial registration, data-sharing, and CONSORT/STROBE compliance required.",
    reviewerProcess: "Single-blind external review with statistical assessment; first decision ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (16.6).",
  },

  // ---- Neurology / psychiatry ----
  {
    id: "neurology", name: "Neurology", abbrev: "Neurology",
    publisher: "American Academy of Neurology (Wolters Kluwer)", country: "United States",
    issnPrint: "0028-3878", issnOnline: "1526-632X", homepage: "https://www.neurology.org/",
    authorGuideUrl: "https://www.neurology.org/author-center", scope: "Clinical neurology.",
    specialties: ["neurology", "neuroscience"],
    acceptedTypes: ["original_investigation", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 9.0, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Strict word/reference limits by article class; structured abstract, trial registration, data-availability statement, and reporting-guideline checklist required.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (9.0).",
  },

  // ---- Infectious disease ----
  {
    id: "cid", name: "Clinical Infectious Diseases", abbrev: "Clin Infect Dis",
    publisher: "Oxford University Press (IDSA)", country: "United States",
    issnPrint: "1058-4838", issnOnline: "1537-6591", homepage: "https://academic.oup.com/cid",
    authorGuideUrl: "https://academic.oup.com/cid/pages/General_Instructions", scope: "Clinical infectious diseases.",
    specialties: ["infectious diseases", "microbiology", "internal medicine"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 7.3, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Major Articles ~3000 words with structured abstract; trial registration, data-sharing, and reporting-guideline checklist required (IDSA-aligned).",
    reviewerProcess: "Single-blind external peer review; first decision typically ~3-5 weeks.",
    decisionTimeDays: 28, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (7.3).",
  },

  // ---- Emerging / regional (ESCI) examples ----
  {
    id: "frontiers-med", name: "Frontiers in Medicine", abbrev: "Front Med",
    publisher: "Frontiers Media", country: "Switzerland",
    issnOnline: "2296-858X", homepage: "https://www.frontiersin.org/journals/medicine",
    authorGuideUrl: "https://www.frontiersin.org/guidelines/author-guidelines", scope: "Broad clinical and translational medicine; open access.",
    specialties: ["general medicine", "internal medicine", "translational"],
    acceptedTypes: ["original_investigation", "systematic_review", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 3.0, quartile: "Q2", metricsYear: 2024 }, oaModel: "gold", apcUsd: 2950,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Article-type-specific structure with structured abstract; data-availability and ethics statements required; reporting-guideline checklists for clinical work. Fee support available.",
    reviewerProcess: "Collaborative identity-disclosed (open) review via interactive platform; ~6-9 weeks to first decision.",
    decisionTimeDays: 60, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / Frontiers fee policy",
    endorsedGuidelines: ["ICMJE", "CONSORT", "PRISMA", "CARE"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (~3.0).",
  },
  {
    id: "medicine-baltimore", name: "Medicine", abbrev: "Medicine (Baltimore)",
    publisher: "Wolters Kluwer", country: "United States",
    issnPrint: "0025-7974", issnOnline: "1536-5964", homepage: "https://journals.lww.com/md-journal/",
    authorGuideUrl: "https://journals.lww.com/md-journal/pages/informationforauthors.aspx", scope: "Broad medicine; open access, large volume.",
    specialties: ["general medicine", "multidisciplinary"],
    acceptedTypes: ["original_investigation", "systematic_review", "case_report"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 1.3, quartile: "Q3", metricsYear: 2024 }, oaModel: "gold", apcUsd: 2050,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Accepts sound studies across all fields; structured abstract, ethics and data statements, and reporting-guideline checklists required; large volume.",
    reviewerProcess: "Single-blind external review; ~4-8 weeks to first decision.",
    decisionTimeDays: 45, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "PRISMA", "CARE", "STROBE"], dataConfidence: "curated", verifyUrls: v,
  },
  {
    id: "heliyon", name: "Heliyon", abbrev: "Heliyon",
    publisher: "Elsevier (Cell Press)", country: "United Kingdom",
    issnOnline: "2405-8440", homepage: "https://www.cell.com/heliyon/home",
    authorGuideUrl: "https://www.cell.com/heliyon/authors", scope: "Multidisciplinary including medicine and health sciences; open access.",
    specialties: ["multidisciplinary", "general medicine", "public health"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "not-indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 3.4, quartile: "Q2", metricsYear: 2024 }, oaModel: "gold", apcUsd: 2200,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Multidisciplinary; sound-science criterion, structured abstract, data-availability and ethics statements, and reporting-guideline checklists required.",
    reviewerProcess: "Single-blind external review with handling editor; ~6-8 weeks to first decision.",
    decisionTimeDays: 50, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "PRISMA", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "PubMed/PMC indexed, not MEDLINE. IF JCR 2024 (~3.4).",
  },

  // =====================================================================
  // EXPANDED SEED (added 2026-05-30) — spanning APC models & specialties.
  // FREE-APC / diamond-OA, subscription/closed, and gold-APC are all
  // represented so users can choose on cost & speed, not just indexing.
  // =====================================================================

  // ---- FREE-APC / diamond / no-fee society & funder journals ----
  {
    id: "world-psychiatry", name: "World Psychiatry", abbrev: "World Psychiatry",
    publisher: "World Psychiatric Association (Wiley)", country: "United States",
    issnPrint: "1723-8617", issnOnline: "2051-5545", homepage: "https://onlinelibrary.wiley.com/journal/20515545",
    authorGuideUrl: "https://onlinelibrary.wiley.com/page/journal/20515545/homepage/forauthors.html",
    scope: "Official journal of the World Psychiatric Association; the highest-impact psychiatry journal, publishing authoritative reviews, forums and special articles on mental health.",
    specialties: ["psychiatry", "mental health", "psychology"],
    acceptedTypes: ["review", "viewpoint", "original_investigation"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "unknown" },
    metrics: { impactFactor: 65.8, quartile: "Q1", metricsYear: 2024 }, oaModel: "diamond",
    apcUsd: 0, apcModel: "none", freeApc: true,
    authorGuidelinesSummary: "Largely invited/commissioned content; unsolicited submissions rare and very short; no submission or publication fee; distributed free to WPA members.",
    reviewerProcess: "Editor-led, highly selective invited review; very high impact, low acceptance for unsolicited work.",
    verifiedAt: "2026-05-30", dataSource: "JCR 2024 / WPA & Wiley site",
    endorsedGuidelines: ["ICMJE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "Highest-IF psychiatry journal (JCR 2024 ~65.8). No APC. Mostly commissioned content.",
  },
  {
    id: "bull-who", name: "Bulletin of the World Health Organization", abbrev: "Bull World Health Organ",
    publisher: "World Health Organization", country: "Switzerland",
    issnPrint: "0042-9686", issnOnline: "1564-0604", homepage: "https://www.who.int/publications/journals/bulletin/",
    authorGuideUrl: "https://www.who.int/publications/journals/bulletin/instructions-to-authors",
    scope: "Public health with a focus on developing countries; policy and practice, research, and systematic reviews of global health relevance.",
    specialties: ["public health", "global health", "epidemiology", "health policy"],
    acceptedTypes: ["original_investigation", "systematic_review", "review", "policy"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 8.4, quartile: "Q1", metricsYear: 2024 }, oaModel: "diamond",
    apcUsd: 0, apcModel: "none", freeApc: true,
    authorGuidelinesSummary: "Research ~3000 words with structured abstract and a 'lessons for global health' angle; STROBE/PRISMA reporting; no APC for any article type.",
    reviewerProcess: "Single-blind external peer review; ~6-10 weeks to first decision.",
    decisionTimeDays: 56, verifiedAt: "2026-05-30", dataSource: "WHO Bulletin site / DOAJ / JCR 2024",
    endorsedGuidelines: ["ICMJE", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "Diamond OA — no article-processing charge. Strong fit for global/LMIC public-health work.",
  },
  {
    id: "eid-cdc", name: "Emerging Infectious Diseases", abbrev: "Emerg Infect Dis",
    publisher: "Centers for Disease Control and Prevention (CDC)", country: "United States",
    issnPrint: "1080-6040", issnOnline: "1080-6059", homepage: "https://wwwnc.cdc.gov/eid/",
    authorGuideUrl: "https://wwwnc.cdc.gov/eid/page/author-resource-center",
    scope: "Global emergence and re-emergence of infectious diseases; surveillance, epidemiology, and applied public-health microbiology.",
    specialties: ["infectious diseases", "epidemiology", "public health", "microbiology"],
    acceptedTypes: ["original_investigation", "review", "case_report", "brief_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 6.6, quartile: "Q1", metricsYear: 2024 }, oaModel: "diamond",
    apcUsd: 0, apcModel: "none", freeApc: true,
    authorGuidelinesSummary: "Strict word limits by article type (e.g. Research <=3500 words); structured abstract; no submission or publication fees; emphasis on public-health impact.",
    reviewerProcess: "Single-blind external peer review plus CDC editorial review; ~6-12 weeks to first decision.",
    decisionTimeDays: 60, verifiedAt: "2026-05-30", dataSource: "CDC EID site / JCR 2024",
    endorsedGuidelines: ["ICMJE", "STROBE", "PRISMA", "CARE"], dataConfidence: "curated", verifyUrls: v,
    notes: "Diamond OA, no APC (US government publication). MEDLINE indexed.",
  },
  {
    id: "wellcome-open-research", name: "Wellcome Open Research", abbrev: "Wellcome Open Res",
    publisher: "F1000 Research (for Wellcome Trust)", country: "United Kingdom",
    issnOnline: "2398-502X", homepage: "https://wellcomeopenresearch.org/",
    authorGuideUrl: "https://wellcomeopenresearch.org/for-authors/article-guidelines",
    scope: "Open-research platform for Wellcome-funded researchers across biomedical and health sciences; publish-then-review model.",
    specialties: ["biomedical", "public health", "general medicine", "multidisciplinary"],
    acceptedTypes: ["original_investigation", "systematic_review", "case_report", "data_note"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "indexed", medline: "not-indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { metricsYear: 2024 }, oaModel: "diamond",
    apcUsd: 0, apcModel: "none", freeApc: true,
    authorGuidelinesSummary: "Open to Wellcome-funded authors; mandatory open data deposition; immediate publication followed by transparent post-publication review; fees covered by Wellcome.",
    reviewerProcess: "Publish-then-review: invited open (signed) peer review after immediate posting; indexing follows passing review.",
    verifiedAt: "2026-05-30", dataSource: "F1000 / Wellcome Open Research site",
    endorsedGuidelines: ["ICMJE", "PRISMA", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "No author fees (Wellcome-funded). Restricted to Wellcome grantees. Publish-review-curate model.",
  },
  {
    id: "jaha", name: "Journal of the American Heart Association", abbrev: "J Am Heart Assoc",
    publisher: "American Heart Association (Wiley)", country: "United States",
    issnOnline: "2047-9980", homepage: "https://www.ahajournals.org/journal/jaha",
    authorGuideUrl: "https://www.ahajournals.org/jaha/author-instructions",
    scope: "Open-access cardiovascular and cerebrovascular research across the spectrum of basic, translational, and clinical science.",
    specialties: ["cardiology", "cardiovascular", "stroke", "internal medicine"],
    acceptedTypes: ["original_investigation", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 4.7, quartile: "Q1", metricsYear: 2024 }, oaModel: "gold", apcUsd: 5400,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original research ~5000 words with structured abstract; trial registration, data-sharing, and AHA reporting-guideline compliance required.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / AHA journals site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "Fully gold OA (APC applies); IF JCR 2024 (~4.7).",
  },

  // ---- Subscription / closed (no APC, paywalled) ----
  {
    id: "lancet-neurol", name: "The Lancet Neurology", abbrev: "Lancet Neurol",
    publisher: "Elsevier", country: "United Kingdom",
    issnPrint: "1474-4422", issnOnline: "1474-4465", homepage: "https://www.thelancet.com/journals/laneur/home",
    authorGuideUrl: "https://www.thelancet.com/laneur/about",
    scope: "Highest-impact clinical neurology; practice-changing trials, reviews, and major findings across neurological disease.",
    specialties: ["neurology", "neuroscience", "stroke"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 45.5, quartile: "Q1", metricsYear: 2024 }, oaModel: "subscription",
    apcModel: "subscription", freeApc: true,
    authorGuidelinesSummary: "Articles with structured summary; mandatory trial registration, data-sharing statement, and reporting-guideline checklist; very selective.",
    reviewerProcess: "Single-blind external review with statistical review; rapid initial triage, weeks for full review.",
    decisionTimeDays: 21, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / Lancet site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "Subscription/closed: no APC to publish, but paywalled. #1 in clinical neurology (JCR 2024, IF 45.5).",
  },
  {
    id: "lancet-oncol", name: "The Lancet Oncology", abbrev: "Lancet Oncol",
    publisher: "Elsevier", country: "United Kingdom",
    issnPrint: "1470-2045", issnOnline: "1474-5488", homepage: "https://www.thelancet.com/journals/lanonc/home",
    authorGuideUrl: "https://www.thelancet.com/lanonc/about",
    scope: "High-impact clinical oncology; practice-changing trials, reviews, and Commission reports.",
    specialties: ["oncology", "cancer", "hematology"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 35.9, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Structured summary; mandatory trial registration, data-sharing statement, and CONSORT/STROBE checklist; highly selective.",
    reviewerProcess: "Single-blind external review with statistical review; rapid initial triage, weeks for full review.",
    decisionTimeDays: 21, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / Lancet site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "Primarily subscription with a paid gold-OA option (hybrid). IF JCR 2024 (35.9).",
  },
  {
    id: "radiology-rsna", name: "Radiology", abbrev: "Radiology",
    publisher: "Radiological Society of North America (RSNA)", country: "United States",
    issnPrint: "0033-8419", issnOnline: "1527-1315", homepage: "https://pubs.rsna.org/journal/radiology",
    authorGuideUrl: "https://pubs.rsna.org/page/radiology/author-instructions",
    scope: "Clinical and translational medical imaging across all modalities and subspecialties.",
    specialties: ["radiology", "imaging", "diagnostics"],
    acceptedTypes: ["original_investigation", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 15.2, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original research ~3000 words with structured abstract and a concise 'key results' summary; STARD/CONSORT/STROBE reporting and data-sharing statement required.",
    reviewerProcess: "Single-blind external peer review with statistical review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "RSNA 2024 impact factors / publisher site",
    endorsedGuidelines: ["ICMJE", "STARD", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF rose to 15.2 (JCR 2024). Subscription with optional paid OA (hybrid).",
  },
  {
    id: "stroke-aha", name: "Stroke", abbrev: "Stroke",
    publisher: "American Heart Association (Wolters Kluwer)", country: "United States",
    issnPrint: "0039-2499", issnOnline: "1524-4628", homepage: "https://www.ahajournals.org/journal/str",
    authorGuideUrl: "https://www.ahajournals.org/str/author-instructions",
    scope: "Cerebrovascular disease: stroke pathophysiology, prevention, acute treatment, and rehabilitation.",
    specialties: ["neurology", "stroke", "cardiovascular", "cerebrovascular"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 8.7, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Strict word/figure limits by article type; structured abstract, trial registration, data-sharing, and reporting-guideline checklist required.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~3-5 weeks.",
    decisionTimeDays: 28, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / AHA journals site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (8.7); highest among peripheral vascular disease journals.",
  },
  {
    id: "bjs", name: "British Journal of Surgery", abbrev: "Br J Surg",
    publisher: "Oxford University Press (BJS Society)", country: "United Kingdom",
    issnPrint: "0007-1323", issnOnline: "1365-2168", homepage: "https://academic.oup.com/bjs",
    authorGuideUrl: "https://academic.oup.com/bjs/pages/General_Instructions",
    scope: "Surgical research across all subspecialties; trials, cohort studies, and systematic reviews of operative practice.",
    specialties: ["surgery", "general surgery", "surgical oncology"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 8.8, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original articles ~3000 words with structured abstract; trial registration, data-sharing, and CONSORT/STROBE/PRISMA checklists required.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~3-5 weeks.",
    decisionTimeDays: 28, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (8.8). Hybrid OA.",
  },

  // ---- Top-tier gold/hybrid OA flagships ----
  {
    id: "nature-medicine", name: "Nature Medicine", abbrev: "Nat Med",
    publisher: "Springer Nature", country: "United Kingdom",
    issnPrint: "1078-8956", issnOnline: "1546-170X", homepage: "https://www.nature.com/nm/",
    authorGuideUrl: "https://www.nature.com/nm/for-authors",
    scope: "Translational and clinical biomedical research bridging laboratory discovery and patient care.",
    specialties: ["translational", "general medicine", "oncology", "immunology", "biomedical"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 50.0, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid", apcUsd: 11690,
    apcModel: "hybrid-apc", freeApc: false,
    authorGuidelinesSummary: "Strict format and length limits; mandatory reporting-summary checklist, data/code availability, trial registration; very selective novelty bar.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~3-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / Nature OA fees",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "ARRIVE"], dataConfidence: "curated", verifyUrls: v,
    notes: "Hybrid; paid gold-OA option ~$11,690 APC. IF JCR 2024 (50.0).",
  },
  {
    id: "jama-network-open", name: "JAMA Network Open", abbrev: "JAMA Netw Open",
    publisher: "American Medical Association", country: "United States",
    issnOnline: "2574-3805", homepage: "https://jamanetwork.com/journals/jamanetworkopen",
    authorGuideUrl: "https://jamanetwork.com/journals/jamanetworkopen/pages/instructions-for-authors",
    scope: "Broad open-access clinical and translational medicine across all specialties; large-volume rigorous journal.",
    specialties: ["general medicine", "public health", "multidisciplinary", "clinical research"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 9.7, quartile: "Q1", metricsYear: 2024 }, oaModel: "gold", apcUsd: 3000,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original Investigation <=3000 words, structured abstract <=350 words; mandatory trial registration, data-sharing statement, and reporting-guideline checklist.",
    reviewerProcess: "Single-blind external peer review with statistical review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / JAMA Network APC page",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA", "STARD"], dataConfidence: "curated", verifyUrls: v,
    notes: "Gold OA APC ~$3,000. IF JCR 2024 (9.7).",
  },
  {
    id: "jmir", name: "Journal of Medical Internet Research", abbrev: "J Med Internet Res",
    publisher: "JMIR Publications", country: "Canada",
    issnOnline: "1438-8871", homepage: "https://www.jmir.org/",
    authorGuideUrl: "https://www.jmir.org/author-information/instructions-for-authors",
    scope: "Digital health, eHealth, health informatics, and technology-enabled care.",
    specialties: ["digital health", "medical informatics", "public health", "telemedicine"],
    acceptedTypes: ["original_investigation", "systematic_review", "review", "viewpoint"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 5.8, quartile: "Q1", metricsYear: 2024 }, oaModel: "gold", apcUsd: 3550,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Structured abstract; CONSORT-EHEALTH for digital trials, plus data-availability and ethics statements; strong methods/reproducibility emphasis.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~4-8 weeks.",
    decisionTimeDays: 42, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / JMIR site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "PRISMA", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "Q1 in Medical Informatics and Health Care Sciences. IF JCR 2024 (5.8).",
  },
  {
    id: "plos-ntds", name: "PLOS Neglected Tropical Diseases", abbrev: "PLoS Negl Trop Dis",
    publisher: "Public Library of Science", country: "United States",
    issnOnline: "1935-2735", homepage: "https://journals.plos.org/plosntds/",
    authorGuideUrl: "https://journals.plos.org/plosntds/s/submission-guidelines",
    scope: "Neglected tropical diseases: epidemiology, pathogenesis, diagnostics, treatment, and control.",
    specialties: ["infectious diseases", "tropical medicine", "global health", "parasitology"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 3.5, quartile: "Q1", metricsYear: 2024 }, oaModel: "gold", apcUsd: 2670,
    apcModel: "waiver-available", freeApc: false,
    authorGuidelinesSummary: "Structured abstract plus a lay 'author summary'; data-availability statement and reporting-guideline checklist required; fee waivers routine for LMIC authors.",
    reviewerProcess: "Single-blind review by academic editor + reviewers; ~5-8 weeks to first decision.",
    decisionTimeDays: 49, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / PLOS fees page",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "Gold OA APC ~$2,670 with routine LMIC waivers. IF JCR 2024 (~3.5).",
  },
  {
    id: "cancers-mdpi", name: "Cancers", abbrev: "Cancers (Basel)",
    publisher: "MDPI", country: "Switzerland",
    issnOnline: "2072-6694", homepage: "https://www.mdpi.com/journal/cancers",
    authorGuideUrl: "https://www.mdpi.com/journal/cancers/instructions",
    scope: "Oncology across basic, translational, and clinical cancer research; open access.",
    specialties: ["oncology", "cancer", "hematology", "radiation oncology"],
    acceptedTypes: ["original_investigation", "systematic_review", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 4.4, quartile: "Q1", metricsYear: 2024 }, oaModel: "gold", apcUsd: 3200,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Structured abstract; data-availability, ethics, and informed-consent statements required; reporting-guideline checklists; rapid-turnaround model.",
    reviewerProcess: "Single-blind external review; fast (~median 30-45 days to first decision).",
    decisionTimeDays: 40, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / MDPI APC page (~2900 CHF)",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA", "CARE"], dataConfidence: "curated", verifyUrls: v,
    notes: "APC ~2900 CHF. IF JCR 2024 (4.4).",
  },
  {
    id: "jcm-mdpi", name: "Journal of Clinical Medicine", abbrev: "J Clin Med",
    publisher: "MDPI", country: "Switzerland",
    issnOnline: "2077-0383", homepage: "https://www.mdpi.com/journal/jcm",
    authorGuideUrl: "https://www.mdpi.com/journal/jcm/instructions",
    scope: "Broad clinical medicine across specialties; open access.",
    specialties: ["general medicine", "internal medicine", "multidisciplinary", "clinical research"],
    acceptedTypes: ["original_investigation", "systematic_review", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 3.0, quartile: "Q1", metricsYear: 2024 }, oaModel: "gold", apcUsd: 2900,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Structured abstract; data-availability, ethics, and consent statements required; reporting-guideline checklists; fast review.",
    reviewerProcess: "Single-blind external review; fast (~median 30-45 days to first decision).",
    decisionTimeDays: 40, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / MDPI APC page (~2600 CHF)",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA", "CARE"], dataConfidence: "curated", verifyUrls: v,
    notes: "APC ~2600 CHF. IF JCR 2024 (~3.0).",
  },
  {
    id: "diagnostics-mdpi", name: "Diagnostics", abbrev: "Diagnostics (Basel)",
    publisher: "MDPI", country: "Switzerland",
    issnOnline: "2075-4418", homepage: "https://www.mdpi.com/journal/diagnostics",
    authorGuideUrl: "https://www.mdpi.com/journal/diagnostics/instructions",
    scope: "Medical diagnostics: laboratory medicine, imaging, pathology, and diagnostic test evaluation.",
    specialties: ["diagnostics", "radiology", "pathology", "laboratory medicine"],
    acceptedTypes: ["original_investigation", "systematic_review", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 3.3, quartile: "Q2", metricsYear: 2024 }, oaModel: "gold", apcUsd: 2900,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Structured abstract; STARD-compliant diagnostic-accuracy reporting and data-availability statement required; rapid review.",
    reviewerProcess: "Single-blind external review; fast (~median 30-45 days to first decision).",
    decisionTimeDays: 40, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / MDPI APC page (~2600 CHF)",
    endorsedGuidelines: ["ICMJE", "STARD", "STROBE", "PRISMA", "CARE"], dataConfidence: "curated", verifyUrls: v,
    notes: "APC ~2600 CHF. IF JCR 2024 (3.3).",
  },
  {
    id: "bmj-open", name: "BMJ Open", abbrev: "BMJ Open",
    publisher: "BMJ Publishing Group", country: "United Kingdom",
    issnOnline: "2044-6055", homepage: "https://bmjopen.bmj.com/",
    authorGuideUrl: "https://bmjopen.bmj.com/pages/authors/",
    scope: "Broad open-access medical research across all disciplines; judged on rigour rather than impact.",
    specialties: ["general medicine", "public health", "epidemiology", "multidisciplinary"],
    acceptedTypes: ["original_investigation", "systematic_review", "study_protocol"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 2.3, quartile: "Q2", metricsYear: 2024 }, oaModel: "gold", apcUsd: 3000,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Accepts study protocols and sound studies regardless of results; mandatory reporting-guideline checklist, data-sharing, and patient/public involvement statement.",
    reviewerProcess: "Open peer review — signed reports published with the article; ~6-10 weeks to first decision.",
    decisionTimeDays: 56, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / BMJ Open author pages",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA", "SPIRIT"], dataConfidence: "curated", verifyUrls: v,
    notes: "Gold OA APC ~£2,390. Publishes protocols. IF JCR 2024 (2.3).",
  },
  {
    id: "bjpsych", name: "The British Journal of Psychiatry", abbrev: "Br J Psychiatry",
    publisher: "Royal College of Psychiatrists (Cambridge University Press)", country: "United Kingdom",
    issnPrint: "0007-1250", issnOnline: "1472-1465", homepage: "https://www.cambridge.org/core/journals/the-british-journal-of-psychiatry",
    authorGuideUrl: "https://www.cambridge.org/core/journals/the-british-journal-of-psychiatry/information/instructions-contributors",
    scope: "All branches of psychiatry with a focus on clinically relevant mental-health research.",
    specialties: ["psychiatry", "mental health", "psychology"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 7.6, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original articles ~3500 words with structured abstract; trial registration, data-sharing, and CONSORT/STROBE/PRISMA checklists required.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~6-8 weeks.",
    decisionTimeDays: 49, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / Cambridge Core",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (7.6). Hybrid OA.",
  },

  // ---- More specialties: gastro, derm, OB/GYN, respiratory, anesthesiology, ophthalmology ----
  {
    id: "gut-bmj", name: "Gut", abbrev: "Gut",
    publisher: "BMJ Publishing Group (BSG)", country: "United Kingdom",
    issnPrint: "0017-5749", issnOnline: "1468-3288", homepage: "https://gut.bmj.com/",
    authorGuideUrl: "https://gut.bmj.com/pages/authors/",
    scope: "Gastroenterology and hepatology: basic, translational, and clinical research across the digestive tract and liver.",
    specialties: ["gastroenterology", "hepatology", "internal medicine"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 25.8, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original research ~5000 words with structured abstract; trial registration, data-sharing, and reporting-guideline checklist required.",
    reviewerProcess: "Single-blind external peer review with statistical review; first decision typically ~3-5 weeks.",
    decisionTimeDays: 28, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / BMJ Gut announcement",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (25.8). Hybrid OA.",
  },
  {
    id: "jama-dermatol", name: "JAMA Dermatology", abbrev: "JAMA Dermatol",
    publisher: "American Medical Association", country: "United States",
    issnPrint: "2168-6068", issnOnline: "2168-6084", homepage: "https://jamanetwork.com/journals/jamadermatology",
    authorGuideUrl: "https://jamanetwork.com/journals/jamadermatology/pages/instructions-for-authors",
    scope: "Clinical and translational dermatology and cutaneous disease.",
    specialties: ["dermatology", "skin disease"],
    acceptedTypes: ["original_investigation", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 11.0, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original Investigation <=3000 words with structured abstract; trial registration, data-sharing statement, and reporting-guideline checklist required.",
    reviewerProcess: "Single-blind external peer review with statistical review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / JAMA Network",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (~11). Hybrid OA.",
  },
  {
    id: "obgyn-green", name: "Obstetrics & Gynecology", abbrev: "Obstet Gynecol",
    publisher: "American College of Obstetricians and Gynecologists (Wolters Kluwer)", country: "United States",
    issnPrint: "0029-7844", issnOnline: "1873-233X", homepage: "https://journals.lww.com/greenjournal/",
    authorGuideUrl: "https://journals.lww.com/greenjournal/pages/informationforauthors.aspx",
    scope: "Obstetrics, gynecology, maternal-fetal medicine, and women's reproductive health (the 'Green Journal').",
    specialties: ["obstetrics", "gynecology", "women's health", "maternal-fetal medicine"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 4.7, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original research ~3000 words with structured abstract; trial registration, data-sharing, and CONSORT/STROBE/PRISMA checklists required.",
    reviewerProcess: "Single-blind external peer review with statistical review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (4.7). Hybrid OA.",
  },
  {
    id: "chest", name: "CHEST", abbrev: "Chest",
    publisher: "American College of Chest Physicians (Elsevier)", country: "United States",
    issnPrint: "0012-3692", issnOnline: "1931-3543", homepage: "https://journal.chestnet.org/",
    authorGuideUrl: "https://journal.chestnet.org/author-information",
    scope: "Pulmonary, critical care, and sleep medicine: clinical research and practice.",
    specialties: ["pulmonology", "respiratory", "critical care", "sleep medicine"],
    acceptedTypes: ["original_investigation", "review", "case_report"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 3.3, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original research ~3000 words with structured abstract; trial registration, data-sharing, and reporting-guideline checklist required.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE", "PRISMA"], dataConfidence: "curated", verifyUrls: v,
    notes: "IF JCR 2024 (~3.3). Hybrid OA.",
  },
  {
    id: "anesthesiology-asa", name: "Anesthesiology", abbrev: "Anesthesiology",
    publisher: "American Society of Anesthesiologists (Wolters Kluwer)", country: "United States",
    issnPrint: "0003-3022", issnOnline: "1528-1175", homepage: "https://pubs.asahq.org/anesthesiology",
    authorGuideUrl: "https://pubs.asahq.org/anesthesiology/pages/authorinstructions",
    scope: "Anesthesiology, perioperative medicine, critical care, and pain medicine.",
    specialties: ["anaesthesia", "anesthesiology", "perioperative", "pain medicine", "critical care"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 9.3, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original research with structured abstract; trial registration, data-sharing, and CONSORT/STROBE checklists required; strong methods/statistics emphasis.",
    reviewerProcess: "Single-blind external peer review with statistical review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / ASA annual report",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "Ranked #1 in anesthesiology (JCR 2024, IF ~9.3). Hybrid OA.",
  },
  {
    id: "ophthalmology-aao", name: "Ophthalmology", abbrev: "Ophthalmology",
    publisher: "American Academy of Ophthalmology (Elsevier)", country: "United States",
    issnPrint: "0161-6420", issnOnline: "1549-4713", homepage: "https://www.aaojournal.org/",
    authorGuideUrl: "https://www.aaojournal.org/content/authorinfo",
    scope: "Clinical ophthalmology and vision science across all subspecialties.",
    specialties: ["ophthalmology", "vision science"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "not-indexed" },
    metrics: { impactFactor: 13.1, quartile: "Q1", metricsYear: 2024 }, oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original research with structured abstract; trial registration, data-sharing, and reporting-guideline checklist required.",
    reviewerProcess: "Single-blind external peer review; first decision typically ~4-6 weeks.",
    decisionTimeDays: 35, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / AAO newsroom",
    endorsedGuidelines: ["ICMJE", "CONSORT", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "Top-ranked ophthalmology journal (JCR 2024). Hybrid OA. Verify exact IF at source.",
  },
  {
    id: "gates-open-research", name: "Gates Open Research", abbrev: "Gates Open Res",
    publisher: "F1000 Research (for the Gates Foundation)", country: "United Kingdom",
    issnOnline: "2572-4754", homepage: "https://gatesopenresearch.org/",
    authorGuideUrl: "https://gatesopenresearch.org/for-authors/article-guidelines",
    scope: "Open-research platform for Gates Foundation-funded global-health and development research; publish-then-review model.",
    specialties: ["global health", "public health", "infectious diseases", "multidisciplinary"],
    acceptedTypes: ["original_investigation", "systematic_review", "data_note", "study_protocol"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { metricsYear: 2024 }, oaModel: "diamond",
    apcUsd: 0, apcModel: "none", freeApc: true,
    authorGuidelinesSummary: "Open to Gates-funded authors; mandatory open data deposition; immediate publication then transparent post-publication review; all fees covered by the Gates Foundation.",
    reviewerProcess: "Publish-then-review: invited open (signed) peer review after immediate posting; indexing follows passing review.",
    verifiedAt: "2026-05-30", dataSource: "F1000 / Gates Open Research site",
    endorsedGuidelines: ["ICMJE", "PRISMA", "STROBE"], dataConfidence: "curated", verifyUrls: v,
    notes: "No author fees (Gates-funded). Restricted to Gates grantees. Publish-review-curate; PubMed/MEDLINE indexed.",
  },
];
