/**
 * Saudi medical/health journals — 100% Saudi-based and Saudi-owned.
 *
 * Curated from public records (publisher sites, NLM Catalog, DOAJ, SJR).
 * Every entry is a journal *headquartered and published in Saudi Arabia*.
 * Indexing/metrics carry honest confidence + official verify links, because
 * status changes over time (ESCI↔SCIE promotion, Scopus re-evaluation) and
 * must be confirmed at the source before a submission decision.
 *
 * This list is intentionally conservative: only journals with a clear, active
 * Saudi institutional home are included. If you maintain this file, verify each
 * journal is still active and Saudi-owned before adding.
 */

import type { JournalRecord } from "./types";

const verify = (extra?: Record<string, string>) => ({
  wos: "https://mjl.clarivate.com/home",
  scopus: "https://www.scopus.com/sources",
  nlm: "https://www.ncbi.nlm.nih.gov/nlmcatalog/journals/",
  doaj: "https://doaj.org/",
  scimago: "https://www.scimagojr.com/journalsearch.php",
  ...(extra || {}),
});

export const saudiJournals: JournalRecord[] = [
  {
    id: "saudi-med-j",
    name: "Saudi Medical Journal",
    abbrev: "Saudi Med J",
    publisher: "Saudi Medical Journal (Armed Forces Hospital, Riyadh)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "0379-5284",
    issnOnline: "1658-3175",
    homepage: "https://smj.org.sa/",
    authorGuideUrl: "https://smj.org.sa/index.php/smj/about/submissions",
    scope:
      "General medicine and biomedical research across all clinical and basic specialties, with a focus on the Gulf and Middle East region.",
    specialties: ["general medicine", "internal medicine", "public health", "surgery", "biomedical"],
    acceptedTypes: ["original_investigation", "systematic_review", "case_report", "brief_report", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "unknown" },
    metrics: { impactFactor: 1.5, quartile: "Q3", metricsYear: 2024 },
    oaModel: "hybrid",
    apcModel: "hybrid-apc",
    authorGuidelinesSummary: "Original articles ~3000 words with structured abstract; ICMJE-compliant disclosures, ethics approval, and reporting-guideline checklist (CONSORT/STROBE/PRISMA) required.",
    reviewerProcess: "Single-blind external peer review; ~6-10 weeks to first decision.",
    decisionTimeDays: 56, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / publisher smj.org.sa",
    endorsedGuidelines: ["ICMJE", "CONSORT", "PRISMA", "STROBE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026; one of the oldest, MEDLINE-indexed Saudi journals (Riyadh). IF corrected to JCR 2024 (1.5).",
  },
  {
    id: "ann-saudi-med",
    name: "Annals of Saudi Medicine",
    abbrev: "Ann Saudi Med",
    publisher: "King Faisal Specialist Hospital & Research Centre",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "0256-4947",
    issnOnline: "0975-4466",
    homepage: "https://www.annsaudimed.net/",
    authorGuideUrl: "https://www.annsaudimed.net/home/forauthors",
    scope:
      "Clinical and translational medicine relevant to Saudi Arabia and the region; original research, reviews, and case reports.",
    specialties: ["general medicine", "internal medicine", "clinical research", "public health"],
    acceptedTypes: ["original_investigation", "systematic_review", "case_report", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 1.8, quartile: "Q3", metricsYear: 2024 },
    oaModel: "diamond",
    apcUsd: 0, apcModel: "none", freeApc: true,
    authorGuidelinesSummary: "Original articles ~3500 words with structured abstract; ethics approval, ICMJE disclosures, and reporting-guideline checklists required; no submission or publication fee.",
    reviewerProcess: "Single-blind external peer review; ~8-12 weeks to first decision.",
    decisionTimeDays: 70, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / annsaudimed.net (no APC)",
    endorsedGuidelines: ["ICMJE", "CONSORT", "PRISMA", "STROBE", "CARE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026; diamond OA — no APC (confirmed on journal homepage). PMC + MEDLINE indexed. IF JCR 2024 (1.8).",
  },
  {
    id: "saudi-j-gastroenterol",
    name: "Saudi Journal of Gastroenterology",
    abbrev: "Saudi J Gastroenterol",
    publisher: "Saudi Gastroenterology Association (Wolters Kluwer Medknow)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1319-3767",
    issnOnline: "1998-4049",
    homepage: "https://www.saudijgastro.com/",
    authorGuideUrl: "https://journals.lww.com/sjga/pages/instructionsforauthors.aspx",
    scope: "Gastroenterology, hepatology, and digestive diseases.",
    specialties: ["gastroenterology", "hepatology", "internal medicine"],
    acceptedTypes: ["original_investigation", "systematic_review", "case_report", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 1.9, quartile: "Q3", metricsYear: 2024 },
    oaModel: "gold", apcUsd: 500,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original/Review articles ~3000 words with structured abstract; ethics approval and reporting-guideline checklists required; modest APC (~USD 500 originals).",
    reviewerProcess: "Single-blind external peer review; ~6-10 weeks to first decision.",
    decisionTimeDays: 56, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / journal APC schedule",
    endorsedGuidelines: ["ICMJE", "CONSORT", "PRISMA", "STROBE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026; SCIE + MEDLINE. Low APC (~USD 500 original / 250 special). IF JCR 2024 (~1.9).",
  },
  {
    id: "saudi-j-kidney-dis-transpl",
    name: "Saudi Journal of Kidney Diseases and Transplantation",
    abbrev: "Saudi J Kidney Dis Transpl",
    publisher: "Saudi Center for Organ Transplantation (Wolters Kluwer Medknow)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1319-2442",
    issnOnline: "1319-2442",
    homepage: "https://www.sjkdt.org/",
    authorGuideUrl: "https://www.sjkdt.org/contributors.asp",
    scope: "Nephrology, dialysis, and organ transplantation.",
    specialties: ["nephrology", "transplantation", "internal medicine", "urology"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "indexed" },
    metrics: { quartile: "Q4", metricsYear: 2024 },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original articles ~3000 words with structured abstract; ethics approval and STROBE/CARE reporting required; APC applies (verify current amount).",
    reviewerProcess: "Single-blind external peer review; ~8-12 weeks to first decision.",
    decisionTimeDays: 70, verifiedAt: "2026-05-30", dataSource: "Scimago / NLM Catalog",
    endorsedGuidelines: ["ICMJE", "STROBE", "CARE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026 (Medknow). ESCI not SCIE; verify current WoS collection before submission.",
  },
  {
    id: "saudi-pharm-j",
    name: "Saudi Pharmaceutical Journal",
    abbrev: "Saudi Pharm J",
    publisher: "Saudi Pharmaceutical Society (Springer, from 2025)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1319-0164",
    issnOnline: "2213-7475",
    homepage: "https://link.springer.com/journal/44446",
    authorGuideUrl: "https://link.springer.com/journal/44446/submission-guidelines",
    scope: "Pharmaceutical sciences, pharmacology, pharmacy practice, and drug research.",
    specialties: ["pharmacy", "pharmacology", "pharmaceutical sciences", "drug research"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "unknown", pmc: "indexed", doaj: "indexed" },
    metrics: { citeScore: 5.8, quartile: "Q1", metricsYear: 2024 },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original/Review articles with structured abstract; ethics approval, data-availability, and reporting-guideline checklists required; gold-OA APC applies (Springer schedule).",
    reviewerProcess: "Single-blind external peer review; ~6-10 weeks to first decision.",
    decisionTimeDays: 56, verifiedAt: "2026-05-30", dataSource: "Scimago / Springer journal page (publisher change 2025)",
    endorsedGuidelines: ["ICMJE", "PRISMA", "CONSORT"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026 — TRANSFERRED from Elsevier to SPRINGER as of 2025 (homepage/URL updated). Official Saudi Pharmaceutical Society journal; Q1, CiteScore ~5.8 (2024). Confirm 2025 JIF at JCR.",
  },
  {
    id: "saudi-j-biol-sci",
    name: "Saudi Journal of Biological Sciences",
    abbrev: "Saudi J Biol Sci",
    publisher: "Saudi Biological Society",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1319-562X",
    issnOnline: "2213-7106",
    homepage: "https://www.sciencedirect.com/journal/saudi-journal-of-biological-sciences",
    authorGuideUrl: "https://www.sciencedirect.com/journal/saudi-journal-of-biological-sciences/publish/guide-for-authors",
    scope: "Biological sciences including molecular biology, microbiology, and biomedical topics.",
    specialties: ["biology", "molecular biology", "microbiology", "biomedical"],
    acceptedTypes: ["original_investigation", "review"],
    indexing: { wos: "none", scopus: "not-indexed", pubmed: "indexed", medline: "not-indexed", pmc: "indexed", doaj: "not-indexed" },
    metrics: { metricsYear: 2024 },
    oaModel: "gold",
    apcModel: "unknown", freeApc: false,
    authorGuidelinesSummary: "No longer accepting submissions — title ceased in 2024. Historical archive remains on ScienceDirect/PMC.",
    reviewerProcess: "N/A — journal discontinued.",
    verifiedAt: "2026-05-30", dataSource: "Elsevier/ScienceDirect + NLM Catalog (ceased v.31(8) 2024)",
    endorsedGuidelines: ["ICMJE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "FLAGGED POSSIBLY INACTIVE: DISCONTINUED by King Saud University in June 2024 (last issue v.31(8), 2024). No longer accepting submissions — retained here only for historical context; do not target for new submissions.",
  },
  {
    id: "saudi-dent-j",
    name: "The Saudi Dental Journal",
    abbrev: "Saudi Dent J",
    publisher: "Saudi Dental Society",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1013-9052",
    issnOnline: "1658-3558",
    homepage: "https://www.sciencedirect.com/journal/the-saudi-dental-journal",
    authorGuideUrl: "https://www.sciencedirect.com/journal/the-saudi-dental-journal/publish/guide-for-authors",
    scope: "Dentistry, oral health, maxillofacial and dental materials research.",
    specialties: ["dentistry", "oral health", "maxillofacial", "dental materials"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "indexed", medline: "unknown", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 2.6, citeScore: 4.0, quartile: "Q2", metricsYear: 2024 },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original/Case/Review articles with structured abstract; ethics approval and CARE/PRISMA reporting required; gold-OA APC applies (Elsevier schedule).",
    reviewerProcess: "Single-blind external peer review; ~6-10 weeks to first decision.",
    decisionTimeDays: 56, verifiedAt: "2026-05-30", dataSource: "Scimago / ScienceDirect",
    endorsedGuidelines: ["ICMJE", "CARE", "PRISMA"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026 (Saudi Dental Society, Elsevier-hosted); ESCI + Scopus, IF JCR 2024 (~2.6).",
  },
  {
    id: "j-family-community-med",
    name: "Journal of Family and Community Medicine",
    abbrev: "J Family Community Med",
    publisher: "Imam Abdulrahman Bin Faisal University (Wolters Kluwer Medknow)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1319-1683",
    issnOnline: "2229-340X",
    homepage: "https://www.jfcmonline.com/",
    authorGuideUrl: "https://www.jfcmonline.com/contributors.asp",
    scope: "Family medicine, primary care, and community/public health.",
    specialties: ["family medicine", "primary care", "public health", "community medicine"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { quartile: "Q3", metricsYear: 2024 },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original/Case/Review articles with structured abstract; ethics approval and STROBE/PRISMA reporting required; Medknow gold-OA fee schedule applies.",
    reviewerProcess: "Single-blind external peer review; ~8-12 weeks to first decision.",
    decisionTimeDays: 70, verifiedAt: "2026-05-30", dataSource: "NLM Catalog / Scimago",
    endorsedGuidelines: ["ICMJE", "STROBE", "PRISMA"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026; MEDLINE + PMC indexed; Imam Abdulrahman Bin Faisal University.",
  },
  {
    id: "j-infect-public-health",
    name: "Journal of Infection and Public Health",
    abbrev: "J Infect Public Health",
    publisher: "Saudi Arabian Ministry of National Guard Health Affairs (Elsevier hosted)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1876-0341",
    issnOnline: "1876-035X",
    homepage: "https://www.sciencedirect.com/journal/journal-of-infection-and-public-health",
    authorGuideUrl: "https://www.sciencedirect.com/journal/journal-of-infection-and-public-health/publish/guide-for-authors",
    scope: "Infectious diseases, infection control, and public health.",
    specialties: ["infectious diseases", "public health", "microbiology", "epidemiology"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "SCIE", scopus: "indexed", pubmed: "indexed", medline: "indexed", pmc: "unknown", doaj: "unknown" },
    metrics: { impactFactor: 4.2, quartile: "Q1", metricsYear: 2024 },
    oaModel: "gold", apcUsd: 2000,
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original/Review articles ~4000 words with structured abstract; ethics approval, data-availability, and STROBE/PRISMA/CONSORT checklists required; gold-OA APC ~USD 2000.",
    reviewerProcess: "Single-blind external peer review; ~6-10 weeks to first decision.",
    decisionTimeDays: 56, verifiedAt: "2026-05-30", dataSource: "JCR 2024 / ScienceDirect (APC ~USD 2000)",
    endorsedGuidelines: ["ICMJE", "STROBE", "PRISMA", "CONSORT"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026; Saudi-owned (MNGHA), Elsevier-hosted, SCIE + MEDLINE. Highest-impact Saudi medical journal. IF JCR 2024 (~4.2).",
  },
  {
    id: "int-j-health-sci",
    name: "International Journal of Health Sciences (Qassim)",
    abbrev: "Int J Health Sci (Qassim)",
    publisher: "Qassim University",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1658-3639",
    issnOnline: "1658-3647",
    homepage: "https://www.ijhs.org.sa/",
    authorGuideUrl: "https://www.ijhs.org.sa/index.php/journal/about/submissions",
    scope: "Broad health sciences, medicine, and allied health.",
    specialties: ["health sciences", "general medicine", "allied health", "public health"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "indexed", medline: "not-indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { impactFactor: 2.1, quartile: "Q3", metricsYear: 2024 },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Broad health-sciences scope; structured abstract, ethics approval, and PRISMA/STROBE reporting required; gold-OA APC applies.",
    reviewerProcess: "Single-blind external peer review; ~8-12 weeks to first decision.",
    decisionTimeDays: 70, verifiedAt: "2026-05-30", dataSource: "Journal site (ijhs.qu.edu.sa) / ESCI",
    endorsedGuidelines: ["ICMJE", "PRISMA", "STROBE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026; Qassim University, PMC-archived, ESCI (IF ~2.1). Reportedly preparing a MEDLINE application — not yet MEDLINE-indexed.",
  },
  {
    id: "saudi-j-anaesth",
    name: "Saudi Journal of Anaesthesia",
    abbrev: "Saudi J Anaesth",
    publisher: "Saudi Anaesthetic Association (Wolters Kluwer Medknow)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1658-354X",
    issnOnline: "0975-3125",
    homepage: "https://www.saudija.org/",
    authorGuideUrl: "https://www.saudija.org/contributors.asp",
    scope: "Anaesthesia, perioperative care, critical care, and pain medicine.",
    specialties: ["anaesthesia", "critical care", "pain medicine", "perioperative"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "indexed", medline: "not-indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { quartile: "Q3", metricsYear: 2024 },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original/Case/Review articles with structured abstract; ethics approval and CONSORT/CARE reporting required; Medknow gold-OA fee schedule applies.",
    reviewerProcess: "Single-blind external peer review; ~8-12 weeks to first decision.",
    decisionTimeDays: 70, verifiedAt: "2026-05-30", dataSource: "PMC / Scimago (ESCI from 2016)",
    endorsedGuidelines: ["ICMJE", "CONSORT", "CARE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026; Saudi Anaesthetic Association (Medknow). ESCI + PubMed/PMC; not MEDLINE-indexed.",
  },
  {
    id: "saudi-j-ophthalmol",
    name: "Saudi Journal of Ophthalmology",
    abbrev: "Saudi J Ophthalmol",
    publisher: "Saudi Ophthalmological Society",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1319-4534",
    issnOnline: "1319-4534",
    homepage: "https://journals.lww.com/sjopt/",
    authorGuideUrl: "https://journals.lww.com/sjopt/pages/instructionsforauthors.aspx",
    scope: "Ophthalmology and vision science.",
    specialties: ["ophthalmology", "vision science"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "indexed", medline: "not-indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { quartile: "Q4", metricsYear: 2024 },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original/Case/Review articles with structured abstract; ethics approval and CARE reporting required; Medknow gold-OA fee schedule applies.",
    reviewerProcess: "Single-blind external peer review; ~8-12 weeks to first decision.",
    decisionTimeDays: 70, verifiedAt: "2026-05-30", dataSource: "Scimago / NLM Catalog",
    endorsedGuidelines: ["ICMJE", "CARE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026; Saudi Ophthalmological Society (Medknow/LWW). ESCI + PubMed/PMC.",
  },
  {
    id: "saudi-j-med-med-sci",
    name: "Saudi Journal of Medicine & Medical Sciences",
    abbrev: "Saudi J Med Med Sci",
    publisher: "Imam Abdulrahman Bin Faisal University (Wolters Kluwer Medknow)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1658-631X",
    issnOnline: "2321-6325",
    homepage: "https://www.sjmms.net/",
    authorGuideUrl: "https://www.sjmms.net/contributors.asp",
    scope: "General medicine and medical sciences.",
    specialties: ["general medicine", "medical sciences", "clinical research"],
    acceptedTypes: ["original_investigation", "case_report", "review", "systematic_review"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "indexed", medline: "not-indexed", pmc: "indexed", doaj: "indexed" },
    metrics: { citeScore: 2.6, quartile: "Q2", metricsYear: 2024 },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Original/Case/Review/systematic articles with structured abstract; ethics approval and PRISMA/STROBE/CARE reporting required; Medknow gold-OA fee schedule applies.",
    reviewerProcess: "Single-blind external peer review; ~8-12 weeks to first decision.",
    decisionTimeDays: 70, verifiedAt: "2026-05-30", dataSource: "Scimago / sjmms.net",
    endorsedGuidelines: ["ICMJE", "PRISMA", "STROBE", "CARE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026; Imam Abdulrahman Bin Faisal University (Medknow). ESCI + Scopus.",
  },
  {
    id: "saudi-j-oral-sci",
    name: "Saudi Journal of Oral Sciences",
    abbrev: "Saudi J Oral Sci",
    publisher: "King Saud University (Wolters Kluwer Medknow)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1658-6816",
    issnOnline: "2348-1471",
    homepage: "https://www.saudijos.org/",
    authorGuideUrl: "https://www.saudijos.org/contributors.asp",
    scope: "Oral and dental sciences.",
    specialties: ["dentistry", "oral health", "oral sciences"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "none", scopus: "unknown", pubmed: "not-indexed", medline: "not-indexed", pmc: "not-indexed", doaj: "indexed" },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Oral/dental original and case articles with structured abstract; ethics approval and CARE reporting required; Medknow gold-OA fee schedule applies.",
    reviewerProcess: "Single-blind external peer review; timeline variable for this emerging title.",
    verifiedAt: "2026-05-30", dataSource: "DOAJ / journal site",
    endorsedGuidelines: ["ICMJE", "CARE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active but emerging (King Saud University, Medknow); DOAJ only, not yet PubMed/Scopus. Confirm indexing before submission.",
  },
  {
    id: "j-nature-sci-medicine",
    name: "Journal of Nature and Science of Medicine",
    abbrev: "J Nat Sci Med",
    publisher: "King Saud bin Abdulaziz University for Health Sciences (Wolters Kluwer Medknow)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "2589-627X",
    issnOnline: "2589-6296",
    homepage: "https://www.jnsmonline.org/",
    authorGuideUrl: "https://www.jnsmonline.org/contributors.asp",
    scope: "Basic and clinical medical sciences.",
    specialties: ["medical sciences", "general medicine", "basic science"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "ESCI", scopus: "indexed", pubmed: "not-indexed", medline: "not-indexed", pmc: "not-indexed", doaj: "indexed" },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Basic/clinical medical-science articles with structured abstract; ethics approval and relevant reporting checklists required; Medknow gold-OA fee schedule applies.",
    reviewerProcess: "Single-blind external peer review; timeline variable.",
    verifiedAt: "2026-05-30", dataSource: "Scimago / jnsmonline.org",
    endorsedGuidelines: ["ICMJE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026; KSAU-HS (Medknow). ESCI + Scopus; not PubMed/MEDLINE indexed.",
  },
  {
    id: "saudi-crit-care-j",
    name: "Saudi Critical Care Journal",
    abbrev: "Saudi Crit Care J",
    publisher: "Saudi Critical Care Society (Wolters Kluwer Medknow)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "2543-1854",
    issnOnline: "2666-1306",
    homepage: "https://www.sccj-sa.org/",
    authorGuideUrl: "https://journals.lww.com/sccj/pages/informationforauthors.aspx",
    scope: "Critical care and intensive care medicine.",
    specialties: ["critical care", "intensive care", "emergency medicine"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "none", scopus: "unknown", pubmed: "not-indexed", medline: "not-indexed", pmc: "not-indexed", doaj: "indexed" },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Critical-care original/case/review articles with structured abstract; ethics approval and CONSORT/CARE reporting required; Medknow gold-OA fee schedule applies.",
    reviewerProcess: "Single-blind external peer review; timeline variable for this newer title.",
    verifiedAt: "2026-05-30", dataSource: "DOAJ / journal site",
    endorsedGuidelines: ["ICMJE", "CONSORT", "CARE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active but newer (Saudi Critical Care Society, Medknow); DOAJ only, indexing still developing.",
  },
  {
    id: "saudi-j-health-sys-res",
    name: "Saudi Journal of Health Systems Research",
    abbrev: "Saudi J Health Syst Res",
    publisher: "Saudi Public Health Authority (Karger hosted)",
    country: "Saudi Arabia",
    saudi: true,
    issnOnline: "2789-1844",
    homepage: "https://karger.com/sjhsr",
    authorGuideUrl: "https://karger.com/sjhsr/pages/guidelines",
    scope: "Health systems, health policy, and public health research.",
    specialties: ["health systems", "health policy", "public health", "epidemiology"],
    acceptedTypes: ["original_investigation", "systematic_review", "review"],
    indexing: { wos: "none", scopus: "unknown", pubmed: "not-indexed", medline: "not-indexed", pmc: "not-indexed", doaj: "unknown" },
    oaModel: "diamond",
    apcUsd: 0, apcModel: "none", freeApc: true,
    authorGuidelinesSummary: "Health-systems/policy articles with structured abstract; ethics approval and STROBE/PRISMA reporting required; Karger-hosted, no APC reported (verify at source).",
    reviewerProcess: "Single-blind external peer review; timeline variable for this newer title.",
    verifiedAt: "2026-05-30", dataSource: "Karger journal page / Saudi Public Health Authority",
    endorsedGuidelines: ["ICMJE", "STROBE", "PRISMA"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active but newer (Saudi Public Health Authority, Karger). Vision-2030-aligned; emerging indexing. APC model reported as no-fee — verify at source.",
  },
  {
    id: "saudi-j-otorhinolaryngol-head-neck",
    name: "Saudi Journal of Otorhinolaryngology Head and Neck Surgery",
    abbrev: "Saudi J Otorhinolaryngol Head Neck Surg",
    publisher: "Saudi Otorhinolaryngology Society (Wolters Kluwer Medknow)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "1319-8491",
    issnOnline: "2543-3458",
    homepage: "https://journals.lww.com/sjoh/",
    authorGuideUrl: "https://journals.lww.com/sjoh/pages/instructionsforauthors.aspx",
    scope: "Otolaryngology, head and neck surgery, audiology.",
    specialties: ["otolaryngology", "ent", "head and neck surgery", "audiology"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "none", scopus: "unknown", pubmed: "not-indexed", medline: "not-indexed", pmc: "not-indexed", doaj: "indexed" },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "ENT/head-and-neck original and case articles with structured abstract; ethics approval and CARE reporting required; Medknow gold-OA fee schedule applies.",
    reviewerProcess: "Single-blind external peer review; timeline variable.",
    verifiedAt: "2026-05-30", dataSource: "DOAJ / journal site",
    endorsedGuidelines: ["ICMJE", "CARE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026 (Saudi ORL Society, Medknow/LWW); DOAJ only, not yet PubMed/Scopus.",
  },
  {
    id: "j-musculoskelet-surg-res",
    name: "Journal of Musculoskeletal Surgery and Research",
    abbrev: "J Musculoskelet Surg Res",
    publisher: "Saudi Orthopedic Association (Scientific Scholar)",
    country: "Saudi Arabia",
    saudi: true,
    issnPrint: "2589-1731",
    issnOnline: "2589-9899",
    homepage: "https://jmsr.org.sa/",
    authorGuideUrl: "https://jmsr.org.sa/instructions-to-author/",
    scope: "Orthopaedics, musculoskeletal surgery, and trauma.",
    specialties: ["orthopaedics", "musculoskeletal", "trauma", "surgery"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "none", scopus: "indexed", pubmed: "not-indexed", medline: "not-indexed", pmc: "not-indexed", doaj: "indexed" },
    oaModel: "gold",
    apcModel: "gold-apc", freeApc: false,
    authorGuidelinesSummary: "Orthopaedic/musculoskeletal original and case articles with structured abstract; ethics approval and CARE/PRISMA reporting required; Scientific Scholar gold-OA fee applies.",
    reviewerProcess: "Single-blind external peer review; timeline variable.",
    verifiedAt: "2026-05-30", dataSource: "Scopus / jmsr.org.sa",
    endorsedGuidelines: ["ICMJE", "CARE", "PRISMA"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active 2026 (Saudi Orthopedic Association, Scientific Scholar); Scopus + DOAJ; not yet PubMed-indexed.",
  },
  {
    id: "saudi-j-emerg-med",
    name: "Saudi Journal of Emergency Medicine",
    abbrev: "Saudi J Emerg Med",
    publisher: "Saudi Society of Emergency Medicine",
    country: "Saudi Arabia",
    saudi: true,
    issnOnline: "2710-0308",
    homepage: "https://www.sjemed.org/",
    authorGuideUrl: "https://www.sjemed.org/index.php/sjem/about/submissions",
    scope: "Emergency medicine and acute care.",
    specialties: ["emergency medicine", "acute care", "trauma"],
    acceptedTypes: ["original_investigation", "case_report", "review"],
    indexing: { wos: "none", scopus: "unknown", pubmed: "not-indexed", medline: "not-indexed", pmc: "not-indexed", doaj: "unknown" },
    oaModel: "diamond",
    apcUsd: 0, apcModel: "none", freeApc: true,
    authorGuidelinesSummary: "Emergency/acute-care original and case articles with structured abstract; ethics approval and CARE reporting required; no APC (diamond OA).",
    reviewerProcess: "Single-blind external peer review; timeline variable for this newer title.",
    verifiedAt: "2026-05-30", dataSource: "Journal site (sjemed.org)",
    endorsedGuidelines: ["ICMJE", "CARE"],
    dataConfidence: "curated",
    verifyUrls: verify(),
    notes: "Active but newer (Saudi Society of Emergency Medicine); diamond OA (no APC). Indexing developing — verify before submission.",
  },
];
